### ISSUE TITLE
NA parameter ignored for read_tsv since 2.0.0

### ISSUE THREAD

**Issue by sbachstein** [tidyverse/readr#1258] opened 2021-08-02 15:10 UTC
Since version 2.0.0 the `na` parameter is ignored entirely for `read_tsv`.

Input `test.csv`:
```
A,B,C
:,k,l
m,:,n
```

Command:
`readr::read_csv('test.csv', na = c(":"))`

Output (as expected):
```
Rows: 2 Columns: 3                                                                                                 
── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (3): A, B, C

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
# A tibble: 2 x 3
  A     B     C    
  <chr> <chr> <chr>
1 NA    k     l    
2 m     NA    n
```
On the other hand

Input `test.tsv`:
```
A	B	C
:	k	l
m	:	n
```

Command:
`readr::read_tsv('test.tsv', na = c(":"))`

Output (no NA replacements):
```
Rows: 2 Columns: 3                                                                                                 
── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (3): A, B, C

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
# A tibble: 2 x 3
  A     B     C    
  <chr> <chr> <chr>
1 :     k     l    
2 m     :     n 
```

**Comment by jimhester** [comment] 2021-08-02 15:20
Duplicate of https://github.com/tidyverse/readr/issues/1255, this is already fixed in the development version of readr.

**Closed by jimhester** 2021-08-02 15:20 UTC
