### ISSUE TITLE
Whenever I do library(readr) my R aborts, and the old version of readr cannot be installed

### ISSUE THREAD

**Issue by parkjooyoung99** [tidyverse/readr#1493] opened 2023-05-06 13:10 UTC
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

1. whenever I load readr in R environment, my R session aborts. This keeps me from installing other packages that requires readr.
2. I tried to downgrade readr by installing old version, but it could not be installed due to the error that I could not figure out. 

```r
Since 1 issue results in session abort and reprex() met error with 2 issue, I am adding link with html file and rmd file where my errors are described. 

rmd file: https://drive.google.com/file/d/1gg7ZLPCWxLOAZ_nFg_qqm-Hs02OtGgaz/view?usp=share_link
html file: https://drive.google.com/file/d/1N7LKiXKWT02iVWAcQdO3IGptiJPyEZ7S/view?usp=share_link
```

**Comment by hadley** [comment] 2023-07-31 21:44
I'd suggest:

1. Closing all open instances of R/RStudio on your computer
2. Installing the pak package `install.packges("pak")`
3. Using pak to install readr with `pak::pak("readr")`

That is more likely to reveal what the problem is.

**Closed by hadley** 2023-07-31 21:44 UTC
