### ISSUE TITLE
read_csv fails on zipped empty csv files

### ISSUE THREAD

**Issue by jnolis** [tidyverse/readr#1025] opened 2019-09-04 18:19 UTC
If you try and open an empty text file with read_csv, you get a 0x0 tibble, which is great and what you want.

While read_csv directly supports reading .gz zipped files, if you try and open an empty text file that is first "gz" zipped you get an error.

It seems like this edge case should have a catch?

```
> read_csv("C:/Users/JNolis2/Desktop/thumbEvents.csv")
# A tibble: 0 x 0
> read_csv("C:/Users/JNolis2/Desktop/thumbEvents.csv.gz")
Error in guess_header_(datasource, tokenizer, locale) : 
  Cannot read file C:/Users/JNolis2/AppData/Local/Temp/RtmpYvChzH/file1c7076e61cff: The volume for a file has been externally altered so that the opened file is no longer valid.
```

**Comment by jimhester** [comment] 2019-09-05 11:59
This is a duplicate of https://github.com/tidyverse/readr/issues/963, it is fixed in the development version of readr.

**Closed by jimhester** 2019-09-05 11:59 UTC
