### ISSUE TITLE
"embedded nul in string" when using stringi after reading with readr 2.0 (devel)

### ISSUE THREAD

**Issue by giocomai** [tidyverse/readr#1208] opened 2021-05-11 21:23 UTC
Processing text imported from a csv file read via vroom, and now with the current dev version of readr, has intermittently led to weird errors.

I have previously reported [this issue with stringi](https://github.com/gagolews/stringi/issues/354), but it immediately emerged that the issue was instead related to `vroom`, as reading the csv with read.csv caused no errors. 

Find reprex below, including a link to a csv file that consistently leads to this issue.

The csv is originally written with `readr`, the contents are parsed from the web via `xml2` and `rvest`, then slightly processed via `stringr`, and passed through an `iconv(to = "UTF-8")` to be on the safe side.

I tried it in different sessions and on different computers, and I always get an error for one of the first lines, but not always the same line.

    Error in stringi::stri_trans_tolower(.) :
    embedded nul in string:

To clarify: if I restart or change computer, then I'd still get the error, but with a different line, which makes me think the problem is not fully with the data itself. As you see from the reprex below, even within the same session I get errors for different lines.

Also, I don't get any error with read.csv, the old readr::read_csv, or if I save the same dataset with just the first hundred lines.

(the dataset is a 65MB csv of press releases of the Kremlin with metadata, originally distributed under a CC-BY license)

``` r
library("dplyr", warn.conflicts = FALSE)
library("readr")


if (file.exists("corpus.csv")==FALSE) {
  download.file(url = "https://testzone.giorgiocomai.eu/vroom_stringi_dataset/president_ru-en_corpus.csv",
                destfile = "corpus.csv")
}


readr::read_csv(file = "corpus.csv") %>%
  dplyr::pull(text) %>%
  stringi::stri_trans_tolower() %>%
  head(10)
#> Rows: 24421 Columns: 7
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr  (5): doc_id, text, title, location, link
#> dbl  (1): id
#> date (1): date
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> Warning: One or more parsing issues, see `problems()` for details
#> Error in stringi::stri_trans_tolower(.): embedded nul in string: 'acting president and prime minister vladimir putin held a meeting with defence minister igor sergeyev\n\ndecember 31, 1999, moscow \n\nmr putin and mr sergeyev discussed a number of routine i\0\001\0\0\0\0'

## Try to read and write again the file, and then read the new one

readr::read_csv(file = "corpus.csv")  %>% 
  readr::write_csv(file = "corpus_rewritten.csv")
#> Rows: 24421 Columns: 7
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr  (5): doc_id, text, title, location, link
#> dbl  (1): id
#> date (1): date
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> Warning: One or more parsing issues, see `problems()` for details


readr::read_csv(file = "corpus_rewritten.csv") %>%
  dplyr::pull(text) %>%
  stringi::stri_trans_tolower() %>%
  head(10)
#> Rows: 24421 Columns: 7
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr  (5): doc_id, text, title, location, link
#> dbl  (1): id
#> date (1): date
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> Warning: One or more parsing issues, see `problems()` for details
#> Error in stringi::stri_trans_tolower(.): embedded nul in string: 'greetings to the 5th russian-azerbaijani forum interregional cooperation: new opportunities for growth\n\njune 23, 2014\n\nvladimir putin sent his greetings to the 5th russian-azerbaijani forum interregional cooperation: new opportunities for growth.\nthe message reads, in part:\n“interregional ties are a key direction for developing the traditionally friendly and good-neighbourly relations between russia and azerbaijan and giving impetus to new projects and initiatives.\nit is important that your authoritative forum, which marks its fifth anniversary this year, continues to gain influence and has provided a useful platform over these years for constructive dialogue on the full range of ties between our countries’ regions. the forum provides an excellent opportunity for developing our considerable cooperation potential in the transport, energy and banking sectors and in investment, agriculture, tourism and education.”\nthe

## Try to read with specs

readr::read_csv(file = "corpus.csv",
                col_types = cols(
                  doc_id = col_character(),
                  text = col_character(),
                  date = col_date(format = ""),
                  title = col_character(),
                  location = col_character(),
                  link = col_character(),
                  id = col_double()
                )) %>%
  dplyr::pull(text) %>%
  stringi::stri_trans_tolower() %>%
  head(10)
#> Warning: One or more parsing issues, see `problems()` for details
#> Error in stringi::stri_trans_tolower(.): embedded nul in string: 'normandy format talks\n\noctober 2, 2015, paris \n\npresident of russia vladimir putin, federal chancellor of germany angela merkel, president of france francois hollande and president of ukraine petro poroshenko met in the normandy format in paris. the four leaders discussed possibilities for resolving the situation in ukraine.\nduring the talks, the leaders touched base on the progress in implementing the most important points in the minsk agreements, confirmed their commitment to the minsk process and stressed that there is no alternative to implementing the minsk agreements.\n earlier, mr putin had bilateral meetings with francois hollande and angela merke\xf0\002\0'

## Read in with read.csv

x <- read.csv("corpus.csv")
y <- dplyr::pull(x, text)
z <- stringi::stri_trans_tolower(y)

head(z, 10)
#>  [1] "acting president vladimir putin addressed the nation on tv...
```
[output cut for brevity]
<sup>Created on 2021-05-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jimhester** [comment] 2021-05-12 12:27
Thank you for opening the issue and for supplying a reproducible example, it is a big help!

I can reproduce the issue, it seems to be an interaction with the lazy loading and stringi, probably due to a bug in vroom. I will look into it and figure out what is going wrong.

As a workaround you can use `lazy = FALSE` in your call to `read_csv()` and this will read the file eagerly, which avoids the issue.

**Comment by jimhester** [comment] 2021-05-12 15:05
So turns out this actually does seem to be a bug in stringi, I commented here https://github.com/gagolews/stringi/issues/354#issuecomment-839820101 about the issue.

**Comment by giocomai** [comment] 2021-05-13 07:12
Thanks a lot for troubleshooting this further!

**Comment by jimhester** [comment] 2021-05-17 19:34
This seems to now be addressed by the stringi package upstream.

**Closed by jimhester** 2021-05-17 19:34 UTC
Labels: bug
