### ISSUE TITLE
More detailed documentation for callback classes?

### ISSUE THREAD

**Issue by Timothy-Barry** [tidyverse/readr#1175] opened 2021-01-27 00:17 UTC
Thank you for this extremely useful package.

I would appreciate if the documentation for the callback classes and `read_delim_chunked` were more detailed. In particular, when using `AccumulateCallback` in conjunction with `read_delim_chunked`, is there a way to modify the accumulator in place (i.e., by reference) to avoid making deep copies? I see there's some stuff about "deep clone" on this [man page](https://readr.tidyverse.org/reference/callback.html), but I'm not exactly sure how to interpret this. Thanks!

**Comment by jimhester** [comment] 2021-01-27 14:18
This is a duplicate of https://github.com/tidyverse/readr/issues/1165

**Closed by jimhester** 2021-01-27 14:18 UTC
