### ISSUE TITLE
read_xxx functions always set the seek offset to the end of the file, preventing "block" reads

### ISSUE THREAD

**Issue by kforner** [tidyverse/readr#705] opened 2017-08-10 09:22 UTC
Example:
``` 
library(readr)
write_csv(iris, 'iris.csv')
con=file('iris.csv', 'rb')
# N.B: only read one row of data
read_csv(con, n_max=1)
seek(con)
[1] 3716
file.size('iris.csv')
[1] 3716
```

This behaviour prevents reading efficiently several blocks, e.g. list(1:1000, 100000:110000) using skip and n_max/

**Comment by jimhester** [comment] 2017-08-10 12:10
This is basically a dupe of https://github.com/tidyverse/readr/issues/76. Basically the way readr works with connections currently is to read _all_ the data in the connection into a raw vector, then parse the raw vector. The plan is to change this in the future, but it will require reworking a fair amount of how readr currently iterates through data.

**Closed** 2017-08-10 12:10 UTC

**Comment by kforner** [comment] 2017-08-10 12:12
not sure. It could be addressed easily by simply calling seek(con, pos) with the relevant position, which can probably be computed by the readr.

**Comment by schelhorn** [comment] 2017-08-10 18:59
See also https://github.com/tidyverse/readr/issues/610
