### ISSUE TITLE
Version 2.0: chunk_size parameter broken in read_delim_chunked function

### ISSUE THREAD

**Issue by timothy-barry** [tidyverse/readr#1248] opened 2021-07-27 03:17 UTC
Hi,

I just updated to version 2.0. The `chunk_size` parameter of the `read_delim_chunked` function does not seem to work. Regardless of the argument that I pass, the chunk size remains fixed at 10000.

Thanks.

EDIT: Here is a reproducible example. Chunk size argument does not work when reading `mtcars.csv`:

```
library(readr)
f <- function(x, pos) print(nrow(x))
read_delim_chunked(file = readr_example("mtcars.csv"),
                   delim = ",",
                   callback = SideEffectChunkCallback$new(f),
                   chunk_size = 5)
```
The output is "32," indicating that all 32 rows were read at once.

**Comment by svraka** [comment] 2021-07-27 15:26
Ran into the same problem, it looks like `chunk_size` is not passed to the `read_delimited_chunked()` call in `read_delim_chunked()`.

https://github.com/tidyverse/readr/blob/3c0e4d88bb1a0b0ba2cad5ce5c719cbd14ab98e1/R/read_delim_chunked.R#L78-L82

**Comment by jimhester** [comment] 2021-07-27 18:41
Thanks for opening the issue and providing a reproducible example.
This was a regression in readr 2.0.0, it should be fixed now in the current master branch.

**Closed** 2021-07-27 18:40 UTC
