### ISSUE TITLE
readr::read_csv excludes milliseconds from timestamps

### ISSUE THREAD

**Issue by bastianilso** [tidyverse/readr#1095] opened 2020-05-15 10:27 UTC
(see original issue at https://github.com/tidyverse/purrr/issues/764)

reading the following csv file with readr::read_csv removes milliseconds in timestamps (formatted `HH:mm:ss.ffff`). Reading with base read.csv works fine.

with the following file
[sampleLog_2020-05-13 10-30-10.0167.zip](https://github.com/tidyverse/readr/files/4633775/sampleLog_2020-05-13.10-30-10.0167.zip)

try:
```r
  df2<-readr::read_csv("sampleLog_2020-05-13 10-30-10.0167.csv")
```
![image](https://user-images.githubusercontent.com/3967945/82040807-72ec1200-96a7-11ea-9f9f-8b99729a1a03.png)

compare to
```r
  df2<-read.csv("sampleLog_2020-05-13 10-30-10.0167.csv")
```
![image](https://user-images.githubusercontent.com/3967945/82040817-77b0c600-96a7-11ea-990c-6b6af4915f19.png)

**Comment by jimhester** [comment] 2020-06-05 15:43
This is a duplicate of https://github.com/tidyverse/readr/issues/883

readr _is_ actually reading the seconds, but R does not display fractional seconds by default.

``` r
library(readr)
data <- read_csv("~/p/readr/sampleLog_2020-05-13 10-30-10.0167.csv")
#> Parsed with column specification:
#> cols(
#>   .default = col_double(),
#>   TimeStamp = col_datetime(format = ""),
#>   Time = col_time(format = ""),
#>   Date = col_date(format = ""),
#>   Event = col_character(),
#>   PupilTime = col_character(),
#>   UnityToPupilTimeOffset = col_character(),
#>   GazeConfidence = col_character(),
#>   EyeCenter0X = col_character(),
#>   EyeCenter0Y = col_character(),
#>   EyeCenter0Z = col_character(),
#>   EyeCenter1X = col_character(),
#>   EyeCenter1Y = col_character(),
#>   EyeCenter1Z = col_character(),
#>   GazeNormal0X = col_character(),
#>   GazeNormal0Y = col_character(),
#>   GazeNormal0Z = col_character(),
#>   GazeNormal1X = col_character(),
#>   GazeNormal1Y = col_character(),
#>   GazeNormal1Z = col_character(),
#>   LocalGazeDirectionX = col_character()
#>   # ... with 17 more columns
#> )
#> See spec(...) for full column specifications.

as.POSIXlt(data$TimeStamp[[1]])$sec
#> [1] 10.0177
```

<sup>Created on 2020-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Closed by jimhester** 2020-06-05 15:43 UTC

**Comment by bastianilso** [comment] 2020-06-07 09:00
@jimhester I tried your command below and it works for the column `Timestamp.` But when I try to do it on the column `Time`, I again only get the result in seconds.

![image](https://user-images.githubusercontent.com/3967945/83964514-f0253400-a8ad-11ea-85c7-8c55a1fb82ab.png)

**Comment by kalenkovich** [comment] 2024-06-17 15:40
The issue is still present 2.1.4.

@jimhester, I don't think this is the display issue: OP's problem (and mine) is with the `Time` column, not `TimeStamp`. `readr` correctly guesses that the `Time` column contains time values and parses it as "hms" but the milliseconds are silently dropped. 

```r
library(readr)

filename <- "sampleLog_2020-05-13 10-30-10.0167.csv"
test <- read_csv(filename)
print(as.double(test$Time[[1]]), digits = 20)
# 37810

test2 <- read_csv(filename, col_types = cols(Time = col_character))
> print(as.double(as_hms(test2$Time[[1]])), digits = 20)
[1] 37810.017699956893921
```

Maybe there is a format specification for `col_time` that would work here? But in any case, it would be useful if `readr` at least produced a warning about the loss of precision.
