### ISSUE TITLE
shouldn't `cols()` use `rlang::list2()` ?

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/readr#1022] opened 2019-08-19 14:21 UTC
It can be convenient to have column specifications stored in a separate list or vector, so we can do `type_convert(df, col_types = cols(!!!specs))` rather than `type_convert(df, col_types = exec(cols, !!!specs))` 

See https://stackoverflow.com/questions/57545892/r-automatically-convert-column-types-based-on-the-values/57558507#57558507

``` r
readr::cols
#> function (..., .default = col_guess()) 
#> {
#>     col_types <- list(...)
#>     is_character <- vapply(col_types, is.character, logical(1))
#>     col_types[is_character] <- lapply(col_types[is_character], 
#>         col_concise)
#>     if (is.character(.default)) {
#>         .default <- col_concise(.default)
#>     }
#>     col_spec(col_types, .default)
#> }
#> <bytecode: 0x0000000016bde598>
#> <environment: namespace:readr>
```

<sup>Created on 2019-08-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment] 2019-08-19 14:53
Duplicate of https://github.com/tidyverse/readr/issues/971

**Closed by jimhester** 2019-08-19 14:53 UTC
