### ISSUE TITLE
write_tsv create fake decimals 

### ISSUE THREAD

**Issue by sylvainschmitt** [tidyverse/readr#1495] opened 2023-05-12 13:22 UTC
Dear developers thanks for the amazing work. However, I encountered a weird behavior from `readr` which seems to invent decimals:

```r
  library(readr)
  cat("VPD\n0.852402144876029", file = "test_in.txt")
  read_tsv("test_in.txt") %>% 
    write_tsv(file = "test_out.txt")
  readLines("test_out.txt")
  # [1] "VPD"                 "0.85240214487602906"
```

I'm using readr 2.1.4

**Comment by hadley** [comment] 2023-07-31 21:39
Duplicate of #1502

**Closed by hadley** 2023-07-31 21:39 UTC
