### ISSUE TITLE
Data format specifications do not render well on pkgdown website

### ISSUE THREAD

**Issue by peterdesmet** [tidyverse/readr#1224] opened 2021-07-08 13:50 UTC
The format specification in `parse_datetime()` at https://readr.tidyverse.org/reference/parse_datetime.html#format-specification doesn't show the examples correctly. E.g.

> Year: "\ 70-99 -> 1970-1999.

Rather than the expected:

> Year: `"%Y"` (4 digits). `"%y"` (2 digits); `00-69` -> `2000-2069`, `70-99` ->`1970-1999`.

<img width="853" alt="Screenshot 2021-07-08 at 15 47 35" src="https://user-images.githubusercontent.com/600993/124933024-d64fa680-e003-11eb-912c-2265c4e20d82.png">

I think this is caused by not correctly escaping with backticks in the documentation at:

https://github.com/tidyverse/readr/blob/aa8a502c62095c4aebba721b23b9a954ebab4e82/R/collectors.R#L266-L294

**Comment by jimhester** [comment] 2021-07-08 13:57
Thanks, this has already been reported and fixed in the development version of the site, it will be addressed in the release version when the next readr version is released, which should be soon.

duplicate of https://github.com/tidyverse/readr/pull/1142, https://github.com/tidyverse/readr/pull/1154, https://github.com/tidyverse/readr/issues/1176

**Closed by jimhester** 2021-07-08 13:57 UTC
