### ISSUE TITLE
skip doesn't work if comment is used

### ISSUE THREAD

**Issue by ldecicco-USGS** [tidyverse/readr#1209] opened 2021-05-11 21:39 UTC
(possibly a bug? if not... a feature request?)
I parse a lot of data that has a bunch of comments in the beginning of the file, each of those lines starts with a `#`, then 2 rows I want to skip....*then* there's the data:

```r
url <- "https://nwis.waterdata.usgs.gov/nwis/qwdata?multiple_site_no=04024430,04024000&multiple_parameter_cds=34247,30234,32104,34220&param_cd_operator=OR&list_of_search_criteria=multiple_site_no,multiple_parameter_cds&group_key=NONE&sitefile_output_format=html_table&column_name=agency_cd&column_name=site_no&column_name=station_nm&inventory_output=0&rdb_inventory_output=file&TZoutput=0&pm_cd_compare=Greater%20than&radio_parm_cds=previous_parm_cds&qw_attributes=0&format=rdb&rdb_qw_attributes=expanded&date_format=YYYY-MM-DD&rdb_compression=value&qw_sample_wide=0&begin_date=2010-11-03"

library(readr)
df <- read_delim(url, comment = "#",
                 skip = 2, col_names = FALSE)
```
Running the above code, I still get the 2 rows I want to skip. I tried other values of skip, (skip = 5) and `df` came back exactly the same as above. I did crash RStudio when I tried a ridiculous value of skip just to see what would happen (that might warrant it's own separate issue).

```r
 head(df)
# A tibble: 6 x 33
  X1     X2     X3    X4    X5    X6    X7    X8    X9    X10   X11   X12   X13  
  <chr>  <chr>  <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr>
1 agenc~ site_~ samp~ samp~ samp~ samp~ samp~ tm_d~ coll~ medi~ proj~ aqfr~ tu_id
2 5s     15s    10d   5d    10d   5d    3s    1s    8s    3s    9s    8s    11s  
3 USGS   04024~ 2011~ 10:35 NA    NA    CDT   K     USGS~ WS    GR11~ NA    NA   
4 USGS   04024~ 2011~ 10:35 NA    NA    CDT   K     USGS~ WS    GR11~ NA    NA

# The lines I want to skip are:
1 agenc~ site_~ samp~ samp~ samp~ samp~ samp~ tm_d~ coll~ medi~ proj~ aqfr~ tu_id
2 5s     15s    10d   5d    10d   5d    3s    1s    8s    3s    9s    8s    11s  
```

I'm using the latest/greatest `readr` version 1.9.9.9000

**Comment by jimhester** [comment] 2021-05-12 12:16
Currently skipping happens before checking for comments, e.g. you would have to use `skip=126` for the data you show. I can see how for this type of data where the comment length presumably varies it would be useful for it to work in the opposite way however. I can see if it would be feasible to look for comments before skipping.

Also if you could reproduce the crash and open a separate issue I can look into that.

**Comment by jimhester** [comment] 2021-05-12 18:35
When I first read this issue I thought it was new behavior in the second edition, but this is actually the way that readr has worked since version 1.3.0 (released in december of 2018). In particular https://github.com/tidyverse/readr/pull/933 introduced this behavior.

In prior versions skip interacted with comments the way your describe.

The current behavior is basically, skip this number of lines in the file before doing anything.

The old behavior was skip this many lines of data.

I am unsure which way would be more intuitive for people and more useful for the most common datasets.

BTW I think a function something like this would work well for reading these datasets with the current readr behavior.

``` r
library(readr)

read_nwis <- function(url) {
  f <- tempfile()
  on.exit(unlink(f))

  download.file(url, f, quiet = TRUE)

  lines <- readLines(f, n = 200)

  last_comment <- max(grep("^#", lines))

  names <- strsplit(lines[last_comment + 1], "\t")[[1]]

  read_tsv(f, skip = last_comment + 2, col_names = names, lazy = FALSE)
}

url <- "https://nwis.waterdata.usgs.gov/nwis/qwdata?multiple_site_no=04024430,04024000&multiple_parameter_cds=34247,30234,32104,34220&param_cd_operator=OR&list_of_search_criteria=multiple_site_no,multiple_parameter_cds&group_key=NONE&sitefile_output_format=html_table&column_name=agency_cd&column_name=site_no&column_name=station_nm&inventory_output=0&rdb_inventory_output=file&TZoutput=0&pm_cd_compare=Greater%20than&radio_parm_cds=previous_parm_cds&qw_attributes=0&format=rdb&rdb_qw_attributes=expanded&date_format=YYYY-MM-DD&rdb_compression=value&qw_sample_wide=0&begin_date=2010-11-03"

read_nwis(url)
#> Rows: 208 Columns: 33
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: "\t"
#> chr  (17): agency_cd, site_no, sample_start_time_datum_cd, tm_datum_rlbty_cd...
#> dbl   (8): hyd_cond_cd, samp_type_cd, parm_cd, result_va, rpt_lev_va, prep_s...
#> lgl   (6): sample_end_dt, sample_end_tm, aqfr_cd, tu_id, body_part_id, lab_s...
#> date  (1): sample_dt
#> time  (1): sample_tm
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> # A tibble: 208 x 33
#>    agency_cd site_no  sample_dt  sample_tm sample_end_dt sample_end_tm
#>    <chr>     <chr>    <date>     <time>    <lgl>         <lgl>        
#>  1 USGS      04024000 2011-03-15 10:35     NA            NA           
#>  2 USGS      04024000 2011-03-15 10:35     NA            NA           
#>  3 USGS      04024000 2011-03-15 10:35     NA            NA           
#>  4 USGS      04024000 2011-03-15 10:35     NA            NA           
#>  5 USGS      04024000 2011-04-20 10:00     NA            NA           
#>  6 USGS      04024000 2011-04-20 10:00     NA            NA           
#>  7 USGS      04024000 2011-04-20 10:00     NA            NA           
#>  8 USGS      04024000 2011-04-20 10:00     NA            NA           
#>  9 USGS      04024000 2011-05-01 13:00     NA            NA           
#> 10 USGS      04024000 2011-05-01 13:00     NA            NA           
#> # … with 198 more rows, and 27 more variables:
#> #   sample_start_time_datum_cd <chr>, tm_datum_rlbty_cd <chr>,
#> #   coll_ent_cd <chr>, medium_cd <chr>, project_cd <chr>, aqfr_cd <lgl>,
#> #   tu_id <lgl>, body_part_id <lgl>, hyd_cond_cd <dbl>, samp_type_cd <dbl>,
#> #   hyd_event_cd <chr>, sample_lab_cm_tx <chr>, parm_cd <dbl>, remark_cd <chr>,
#> #   result_va <dbl>, val_qual_tx <chr>, meth_cd <chr>, dqi_cd <chr>,
#> #   rpt_lev_va <dbl>, rpt_lev_cd <chr>, lab_std_va <lgl>, prep_set_no <dbl>,
#> #   prep_dt <dbl>, anl_set_no <chr>, anl_dt <dbl>, result_lab_cm_tx <chr>,
#> #   anl_ent_cd <chr>
```

<sup>Created on 2021-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by ldecicco-USGS** [comment] 2021-05-12 18:49
Oh, sorry! I'm using the vigorous testing of the new version of `readr` to see if I can streamline some of my older code. Yeah, the script you have there is what I do. I like to test every couple of years if I could somehow skip the double-reading part (one to figure out the number of comment lines, and one to read the rest of the data). 

As I was testing more of my queries...I was reminded that we have some data that includes `#` IN the data as well, so I don't think I'll be able to take advantage of the `comment` argument ever anyway (because for our data, the `#` at the start of the line means "this line is a comment", and once the data starts, there are no more comments).

Even though I won't be using the comment + skip combo...it might be nice to add in the documentation for the arguments...something like:

comment:  string used to identify comments. Any text after the comment characters will be silently ignored. If the "skip" argument is specified, comments will only be removed after the number of lines to be skipped.

skip: Number of lines to skip before reading data. These lines are initially skipped, any other argument is applied after the skip.

(or something like that.....)

**Closed** 2021-05-12 20:05 UTC

**Comment by jimhester** [comment] 2021-05-12 20:29
I did a little survey of CSV reading functions (utils::read.csv, pandas, CSV.jl) and they all basically operate how `read_csv()` does now with respect to skip and comments. So I think the current behavior is the most consistent and we will stick with that.

I tried to mention this interaction in the documentation, so hopefully that will clarify things for people in the future.
