### ISSUE TITLE
read_tsv fails to read all lines

### ISSUE THREAD

**Issue by sonhan18** [tidyverse/readr#999] opened 2019-05-24 06:00 UTC
I got a problem with readr::read_tsv to read tsv files. Here is the detail:

Everything is ok with the 'n_max' under 94716, but error blow: 

Error in read_tokens_(data, tokenizer, col_specs, col_names, locale_,  : 
  Invalid multibyte sequence

when 'n_max' is over 94716. Things seems to be less column values against the column names over 94716 lines somewhere. How to solve it ?  Pretty thanks so much !

**Comment by cderv** [comment] 2019-05-24 06:17
It could be something special with a charecter in line after 94176. Maybe encoding related. 🤔 
Can you share some data around this lines where the issue is ? or provide directly a reprex ?
without this, it is difficult to help you.

**Comment by sonhan18** [comment] 2019-05-24 07:34
Thanks for your response. 
# Here is the code with encoding 'CP932' and the first line.
 df1 <- read_tsv("01studysample_SCIData.tsv", n_max = 94715,  col_names = TRUE,
                locale = locale(encoding = "CP932") )
 A tibble: 94,715 x 20
     X1 receipt_num receipt_buydate receipt_buytime G_gyoutai_name       receipt_value cat1   cat2   cat3  
  <dbl>       <dbl> <date>          <drtn>          <chr>                        <dbl> <chr>  <chr>  <chr> 
1     0    53471411 2014-05-31      21:41           コンビニエンスストア           450 食料品 たばこ たばこ
  cat4   product_name  unit price volume tanka    id gender age   married job           
  <chr>  <chr>        <dbl> <dbl>  <dbl> <dbl> <dbl> <chr>  <chr> <chr>   <chr>         
1 たばこ KOOL MILDS       1   450  20000   450 10020 男性   50代  既婚    正社員・公務員
 … with 9.471e+04 more rows

# And the error with n_max = 94176.
df1 <- read_tsv("01studysample_SCIData.tsv", n_max = 94716, col_names = TRUE,
                locale = locale(encoding = "CP932") )
Error in read_tokens_(data, tokenizer, col_specs, col_names, locale_,  : 
  Invalid multibyte sequence

**Comment by jimhester** [comment] 2019-05-24 12:21
Almost surely this is because there is data in the file with the wrong encoding. This is unlikely to be an issue in readr, rather it is something that needs to be fixed in the file before it can be read. 

This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

**Comment by sonhan18** [comment] 2019-05-27 00:12
Thank you for your advise. I'will try it for rstudio community. Thanks so much, cderv and  jimhester.

**Closed** 2019-05-27 00:12 UTC
