### ISSUE TITLE
Reading a specific file causes crashes and hangs

### ISSUE THREAD

**Issue by rmcd1024** [tidyverse/readr#1168] opened 2021-01-07 19:35 UTC
I have a reproducible crash with `read_csv` version 1.4 and the development version (1.4.0.9000). The problem does not occur with `readr` 1.3.1.

When run from the command line on Ubuntu 18.04, the script below (run as rmarkdown) generates the crash. When run from RStudio, compilation of the rmarkdown script sometimes hangs, other times there is a similar crash message.  I have verified the problem on two Linux and one Windows machine.

```{r}
library(tidyverse)
#b0 <- data.table::fread('~/test/babynames.csv')
b1 = readr::read_csv('~/test/babynames.csv')
sessionInfo()
```

generates this crash log:  [test2_crash.log](https://github.com/tidyverse/readr/files/5783537/test2_crash.log)

If line 2 (`fread`) is commented (as above), the crash occurs
If lines 1 and 2 are commented, the crash does not occur
If no lines are commented, the crash does not occur

`babynames.csv` ([babynames_sorted.zip](https://github.com/tidyverse/readr/files/5783529/babynames_sorted.zip)) has a different sort order than in the package. Otherwise I have verified that it is substantively the same.

Here is the output from `sessionInfo` when the program does not crash:

```
## R version 4.0.3 (2020-10-10)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 18.04.5 LTS
## 
## Matrix products: default
## BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
## LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] forcats_0.5.0   stringr_1.4.0   dplyr_1.0.2     purrr_0.3.4    
## [5] readr_1.4.0     tidyr_1.1.2     tibble_3.0.4    ggplot2_3.3.3  
## [9] tidyverse_1.3.0
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_1.0.5        cellranger_1.1.0  pillar_1.4.7      compiler_4.0.3   
##  [5] dbplyr_2.0.0      tools_4.0.3       digest_0.6.27     lubridate_1.7.9.2
##  [9] jsonlite_1.7.2    evaluate_0.14     lifecycle_0.2.0   gtable_0.3.0     
## [13] pkgconfig_2.0.3   rlang_0.4.10      reprex_0.3.0      cli_2.2.0        
## [17] rstudioapi_0.13   DBI_1.1.0         yaml_2.2.1        haven_2.3.1      
## [21] xfun_0.19         withr_2.3.0       xml2_1.3.2        httr_1.4.2       
## [25] knitr_1.30        fs_1.5.0          generics_0.1.0    vctrs_0.3.6      
## [29] hms_0.5.3         grid_4.0.3        tidyselect_1.1.0  data.table_1.13.6
## [33] glue_1.4.2        R6_2.5.0          fansi_0.4.1       readxl_1.3.1     
## [37] rmarkdown_2.6     modelr_0.1.8      magrittr_2.0.1    ps_1.5.0         
## [41] backports_1.2.1   scales_1.1.1      ellipsis_0.3.1    htmltools_0.5.0  
## [45] rvest_0.3.6       assertthat_0.2.1  colorspace_2.0-0  stringi_1.5.3    
## [49] munsell_0.5.0     broom_0.7.3       crayon_1.3.4
```

**Comment by jimhester** [comment] 2021-01-08 14:48
Unfortunately I cannot reproduce this, please make sure you have the latest CRAN version of the cpp11 package installed and re-compile readr 1.4.0 and see if that fixes the issue.

**Comment by rmcd1024** [comment] 2021-01-08 18:04
By "recompile" do you mean install from source? I have `cpp11` 0.2.4 installed. I reinstalled `readr` 1.4.0 from source and the crash still occurs. A few things:

1. I experimented with loading `tidyverse` components individually to see if there was one package interaction that was causing the problem. In Windows, it seems to depend just on whether `tidyverse` itself is loaded, the set of individual packages doesn't seem to matter. In Linux, loading ggplot2 and dplyr are sufficient to cause the problem.

2. The problem is reproducible when rendering the Rmd file, but seems to happen only sporadically if you execute the commands individually in the console.

3. In Windows, within RStudio, the script stalls during the render. The output in the rmarkdown tab just hangs. At the command line, the script exits silently without producing the html file. In Linux, by contrast, I get the crash and dump information I've already shared.

Here's the Rmd file I'm rendering using Rscript: [test2a.zip](https://github.com/tidyverse/readr/files/5788658/test2a.zip)  This is the variant that crashes in Linux (all `library` commands are commented except `ggplot2` and `dplyr`).

To provide some context, I discovered this issue when preparing a video lecture on a Windows machine. Every time I got to a certain point, RStudio would hang in the middle of knitting. No explicit crash and no error message, it would just stop cold when rendering the chunk containing `read_csv`. I created the reproducible example on one Linux machine and then verified on a second. I know you can't do anything without reproducing, but I thought it might help to understand the provenance of the report.

**Comment by jimhester** [comment] 2021-05-11 13:04
I don't doubt you are experiencing this issue, but as I am unable to reproduce it on a windows machine or on linux.

As such I am going to close this issue, however if you are able to reproduce it with a smaller example that would help running it down and we can re-open this issue.

**Closed by jimhester** 2021-05-11 13:04 UTC
Labels: reprex

**Comment by rmcd1024** [comment] 2021-05-15 19:37
Just to close this on my end, the problem persists with readr 1.40, but it does *not* occur with the current development version.
