### ISSUE TITLE
format_delim bug when starting characters are NA

### ISSUE THREAD

**Issue by Tonyynot14** [tidyverse/readr#1324] opened 2021-11-10 20:14 UTC
When using format_delim on a dataframe that includes the attributes that start with the value NA it quotes them. For example, I have a field that contains the value NAE in a column and it still quotes the values. 
Here is an example. This probably is not intended and looks like it may have something to do with the vroom package but I am unsure. 

library(readr)
employee <- c('John Doe','NAEasdasdsadasds Gynn','Jolie Hope')
salary <- c(21000, 23400, 26800)
startdate <- as.Date(c('2010-11-1','2008-3-25','2007-3-14'))

data = data.frame( employee,salary,startdate)
create_delim<- format_delim(data,delim = "|")
print(create_delim)
#this prints "employee|salary|startdate\nJohn Doe|21000|2010-11-01\n\"NAEasdasdsadasds Gynn\"|23400|2008-03-25\nJolie Hope|26800|2007-03-14\n"

**Comment by sbearrows** [comment] 2022-04-07 00:22
Thanks for opening this issue! We have another open issue tracking this so I'm marking this one as a duplicate.

Duplicate of https://github.com/tidyverse/readr/issues/1386

**Closed** 2022-04-07 00:23 UTC
Labels: bug
