### ISSUE TITLE
read_csv with commas inside double quoted strings?

### ISSUE THREAD

**Issue by ogsj** [tidyverse/readr#776] opened 2018-01-12 09:05 UTC
trying to read a csv like this:

id, number1, string, number2
1, 1, "1,2,3", 3
2, 3, "12,3", 4

with read_csv("data", quote = '"') 

but it does not parse it correctly?

read.csv("data", quote = '"') works as excepected...

**Comment by jimhester** [comment] 2018-01-12 16:02
This is caused by the spaces between the `,` and the values in your examples, e.g. this is a duplicate of https://github.com/tidyverse/readr/issues/668 and is fixed in the devel version of readr.

**Closed by jimhester** 2018-01-12 16:02 UTC

**Comment by ogsj** [comment] 2018-01-12 18:21
I don't think it is because of spaces. I've removed them and the result is the same. read_csv removes the commas within quoted fields regardless. Will try the dev version though, thanks

**Comment by ogsj** [comment] 2018-01-12 18:44
The devel readr (1.2.0) does not parse the file correctly, the field "1,2,3" turns into 123. If I set cols to "character" it works fine, but without it the commas are removed and the field becomes class numeric?

**Comment by batpigandme** [comment] 2018-01-12 18:52
If you're still having this problem with the most recent dev version (`tidyverse/readr@f2daa84`), could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same structure etc.

**Comment by ogsj** [comment] 2018-01-12 19:29
``` r
indata <- data.frame(col1 = 1,
                   col2 = "1,2,3",
                   col3 = 1)

write.csv(indata, "mycsv.csv", quote = TRUE, row.names = FALSE)

library(readr)
dat <- read_csv("mycsv.csv", quote= '"')
#> Parsed with column specification:
#> cols(
#>   col1 = col_double(),
#>   col2 = col_number(),
#>   col3 = col_double()
#> )
```

**Comment by jimhester** [comment] 2018-01-12 19:32
Oh, right now I see, the issue is not with the quoting at all, but because `1, 2, 3` is being guessed as a number. So this is working as intended using the flexible numeric parser. If you want the `string` column to be a character instead, you need to tell readr that.

``` r
x <- c(
'id, number1, string, number2
1, 1, "1,2,3", 3
2, 3, "12,3", 4')

library(readr)
read_csv(x, quote='"', col_types = cols(string = "c"))
#> # A tibble: 2 x 4
#>      id number1 string number2
#>   <dbl>   <dbl> <chr>    <dbl>
#> 1  1.00    1.00 1,2,3     3.00
#> 2  2.00    3.00 12,3      4.00
```

Created on 2018-01-12 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).
