### ISSUE TITLE
read_* with n_max

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/readr#700] opened 2017-07-31 18:06 UTC
I have some big csv files where I need to check the first couple of rows. Even though I use `n_max = 5` it seems that the whole file is read in (at least it takes forever).
The base functions behave much better here as they only read in the required parts.

**Comment by jimhester** [comment] 2017-07-31 18:38
I imagine you are reading the files from a connection object? I.e. they are gzipped or something? When readr reads from a connection it reads the full file into memory first, then parses it. You will need to use a regular file to read it partially.

**Comment by mgirlich** [comment] 2017-07-31 20:23
I read the files from the network (i.e. file is a url starting with "https") and the files aren't zipped. It would be great if the readr functions wouldn't read in the whole file over a connection when only a small part of it is necessary.

**Comment by jimhester** [comment] 2017-07-31 20:54
Yes, we agree, but making that change will require a fair amount of re-writing in the readr internals, which is why this has not yet been done.

**Comment by jimhester** [comment] 2017-08-10 12:25
Closing as this is a dupe of https://github.com/tidyverse/readr/issues/76

**Closed by jimhester** 2017-08-10 12:25 UTC
