### ISSUE TITLE
?parse_datetime garbled

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/readr#1195] opened 2021-04-14 02:56 UTC
Locally and on the web: https://readr.tidyverse.org/reference/parse_datetime .

![Screenshot from 2021-04-14 05-38-56](https://user-images.githubusercontent.com/1741643/114651178-c0239a00-9ce3-11eb-8252-4e55d12e4e4b.png)

On the same page: `parse_date()`, `parse_time()`, `col_datetime()`, `col_date()`, `col_time()` .

**Comment by jimhester** [comment] 2021-04-14 11:51
Duplicate of https://github.com/tidyverse/readr/issues/1176, https://github.com/tidyverse/readr/pull/1142, will be fixed with the next readr release.

**Closed by jimhester** 2021-04-14 11:51 UTC
