### ISSUE TITLE
Can't read a csv file encoded with  "ISO-8859-1"

### ISSUE THREAD

**Issue by lsaravia** [tidyverse/readr#1107] opened 2020-06-10 00:37 UTC
I tried to read a csv file and it reads only 1 logical column and there should be many different columns, beware it's a big file (76MB). 

```r
csv_fname1 <- "https://sisa.msal.gov.ar/datos/descargas/covid-19/files/Covid19Casos.csv"
cor_nac <- read_csv(csv_fname1,locale = locale(encoding = "ISO-8859-1"))

Parsed with column specification:
cols(
  col_logical()
)
|==========================================================================================================================| 100%   76 MB
Warning: 556694 parsing failures.
row col           expected     actual                    file
  1     1/0/T/F/TRUE/FALSE            'Data/Covid19Casos.csv'
  2     1/0/T/F/TRUE/FALSE            'Data/Covid19Casos.csv'
  2  -- 1 columns          25 columns 'Data/Covid19Casos.csv'
  3     1/0/T/F/TRUE/FALSE            'Data/Covid19Casos.csv'
  4     1/0/T/F/TRUE/FALSE            'Data/Covid19Casos.csv'
... ... .................. .......... .......................
See problems(...) for more details.

```
So I download it and tried with the base functions and it seems to work, but I have to add `skipNul = TRUE`,  it seems to be a problem with read_csv()

```r
cor_nac <- read.csv(csv_fname1,stringsAsFactors = FALSE,fileEncoding = "ISO-8859-1",skipNul = TRUE)

str(cor_nac)
'data.frame':	185564 obs. of  25 variables:
 $ ÿþid_evento_caso                : int  672064 717629 717926 718029 718055 718058 719404 719405 720253 724133 ...
 $ sexo                            : chr  "M" "F" "F" "F" ...
 $ edad                            : int  52 46 41 52 34 31 47 30 28 24 ...
 $ edad_años_meses                 : chr  "Años" "Años" "Años" "Años" ...
 $ residencia_pais_nombre          : chr  "Argentina" "Argentina" "Argentina" "Argentina" ...
 $ residencia_provincia_nombre     : chr  "Buenos Aires" "Buenos Aires" "CABA" "Buenos Aires" ...
 $ residencia_departamento_nombre  : chr  "Florencio Varela" "Pergamino" "COMUNA 12" "La Plata" ...
 $ carga_provincia_nombre          : chr  "Buenos Aires" "Buenos Aires" "CABA" "Buenos Aires" ...
 $ fecha_inicio_sintomas           : chr  "2020-05-29" "2020-01-29" "2020-01-23" "2020-01-29" ...
 $ fecha_apertura                  : chr  "" "2020-01-31" "2020-01-31" "2020-01-31" ...
 $ sepi_apertura                   : int  44 5 5 5 5 5 6 6 6 7 ...
 $ fecha_internacion               : chr  "" "" "" "" ...
 $ cuidado_intensivo               : chr  "NO" "NO" "NO" "NO" ...
 $ fecha_cui_intensivo             : chr  "" "" "" "" ...
 $ fallecido                       : chr  "NO" "NO" "NO" "NO" ...
 $ fecha_fallecimiento             : chr  "" "" "" "" ...
 $ asistencia_respiratoria_mecanica: chr  "NO" "NO" "NO" "NO" ...
 $ carga_provincia_id              : int  6 6 2 6 2 2 2 2 2 6 ...
 $ origen_financiamiento           : chr  "Público" "Público" "Público" "Público" ...
 $ Clasificacion                   : chr  "Caso Descartado" "Caso Descartado" "Caso Invalidado Epidemiologicamente" "Caso Invalidado Epidemiologicamente" ...
 $ clasificacion_resumen           : chr  "Descartado" "Descartado" "Descartado" "Descartado" ...
 $ residencia_provincia_id         : int  6 6 2 6 2 2 6 14 2 6 ...
 $ fecha_diagnostico               : chr  "2020-06-01" "" "" "" ...
 $ residencia_departamento_id      : int  274 623 12 441 0 0 441 98 11 658 ...
 $ ultima_actualizacion            : chr  "2020-06-09" "2020-06-09" "2020-06-09" "2020-06-09" ...
```

**Comment by jimhester** [comment] 2020-06-10 11:08
This file is _not_ in ISO-8859-1, it is in UTF-16LE, readr does not currently support multi-byte encodings like UTF-16LE, see https://github.com/tidyverse/readr/issues/306.

You can read this with readr by first using iconv to convert it to UTF-8, e.g.

``` r
file <- "~/p/readr/Covid19Casos.csv"
x_utf16 <- readBin(file, "raw", n = file.size(file))
x_utf8 <- iconv(list(x_utf16), from = "UTF-16LE", to = "UTF-8", toRaw = TRUE)[[1]]
readr::read_csv(x_utf8)
#> Parsed with column specification:
#> cols(
#>   .default = col_character(),
#>   id_evento_caso = col_double(),
#>   edad = col_double(),
#>   fecha_inicio_sintomas = col_date(format = ""),
#>   fecha_apertura = col_date(format = ""),
#>   sepi_apertura = col_double(),
#>   fecha_internacion = col_date(format = ""),
#>   fecha_cui_intensivo = col_date(format = ""),
#>   fecha_fallecimiento = col_date(format = ""),
#>   fecha_diagnostico = col_date(format = ""),
#>   ultima_actualizacion = col_date(format = "")
#> )
#> See spec(...) for full column specifications.
#> # A tibble: 185,564 x 25
#>    id_evento_caso sexo   edad edad_años_meses residencia_pais… residencia_prov…
#>             <dbl> <chr> <dbl> <chr>           <chr>            <chr>           
#>  1         672064 M        52 Años            Argentina        Buenos Aires    
#>  2         717629 F        46 Años            Argentina        Buenos Aires    
#>  3         717926 F        41 Años            Argentina        CABA            
#>  4         718029 F        52 Años            Argentina        Buenos Aires    
#>  5         718055 F        34 Años            Argentina        CABA            
#>  6         718058 F        31 Años            Argentina        CABA            
#>  7         719404 M        47 Años            Argentina        Buenos Aires    
#>  8         719405 M        30 Años            Argentina        Córdoba         
#>  9         720253 M        28 Años            Argentina        CABA            
#> 10         724133 M        24 Años            Argentina        Buenos Aires    
#> # … with 185,554 more rows, and 19 more variables:
#> #   residencia_departamento_nombre <chr>, carga_provincia_nombre <chr>,
#> #   fecha_inicio_sintomas <date>, fecha_apertura <date>, sepi_apertura <dbl>,
#> #   fecha_internacion <date>, cuidado_intensivo <chr>,
#> #   fecha_cui_intensivo <date>, fallecido <chr>, fecha_fallecimiento <date>,
#> #   asistencia_respiratoria_mecanica <chr>, carga_provincia_id <chr>,
#> #   origen_financiamiento <chr>, Clasificacion <chr>,
#> #   clasificacion_resumen <chr>, residencia_provincia_id <chr>,
#> #   fecha_diagnostico <date>, residencia_departamento_id <chr>,
#> #   ultima_actualizacion <date>
```

<sup>Created on 2020-06-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment] 2020-06-11 20:43
Since this is really a a duplicate of the feature request in #306 I will close this issue.

**Closed by jimhester** 2020-06-11 20:43 UTC
