### ISSUE TITLE
Newline error using read_lines

### ISSUE THREAD

**Issue by saulo1305** [tidyverse/readr#1294] opened 2021-09-03 20:17 UTC
I used to read a file using read_lines under readr version 1.4.0.
But with readr version 2.0.1, it throws newline error "Files must end with a newline".

Here is the reading expression:

`dger <- read_lines("C:\\Users\\saulo\\Downloads\\CB_LEN_A-5_2021_r1\\CB_LEN_A-5_2021_r1\\NEWAVE\\dger.txt)`

The file:

[dger.txt](https://github.com/tidyverse/readr/files/7108292/dger.txt)

**Comment by jimhester** [comment] 2021-09-07 13:19
Thanks for opening the issue, unfortunately I cannot reproduce the error you describe with the file in question.

``` r
readr::read_lines("https://github.com/tidyverse/readr/files/7108292/dger.txt")
#>  [1] "NEWAVE 27 - CASO BASE GARANTIA FISICA LEN A-5/2021"                                                                                       
#>  [2] "TIPO DE EXECUCAO        1   (=1 RODADA COMPLETA; =0 SO SIM. FINAL)"                                                                       
#>  [3] "DURACAO DO PERIODO      1"                                                                                                                
#>  [4] "No. DE ANOS DO ESTUDO   5"                                                                                                                
#>  [5] "MES INICIO PRE-ESTUDO  01"                                                                                                                
#>  [6] "MES INICIO DO ESTUDO   01"                                                                                                                
#>  [7] "ANO INICIO DO ESTUDO 2026"                                                                                                                
#>  [8] "No. DE ANOS PRE        10"                                                                                                                
#>  [9] "No. DE ANOS POS         5"                                                                                                                
#> [10] "No. DE ANOS POS FINAL   5"                                                                                                                
#> [11] "IMPRIME DADOS           1"                                                                                                                
#> [12] "IMPRIME MERCADOS        1"                                                                                                                
#> [13] "IMPRIME ENERGIAS        1"                                                                                                                
#> [14] "IMPRIME M. ESTOCAS      1"                                                                                                                
#> [15] "IMPRIME SUBSISTEMA      1"                                                                                                                
#> [16] "No MAX. DE ITER.       45"                                                                                                                
#> [17] "No DE SIM. FORWARD    200"                                                                                                                
#> [18] "No DE ABERTURAS        20 0000                (2o CAMPO: ABERTURA VARIAVEL /  =0 NAO CONSIDERA; =1 CONSIDERA)"                            
#> [19] "No DE SERIES SINT.   2000"                                                                                                                
#> [20] "ORDEM MAX. PAR(P)       6"                                                                                                                
#> [21] "ANO INICIAL HIST.    1931   1"                                                                                                            
#> [22] "CALCULA VOL.INICIAL     0   0=USA REG 20 ; 1= CALCULA EARM. INICIAL"                                                                      
#> [23] "VOLUME INICIAL  -%   XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X"             
#> [24] " POR REE             100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0"             
#> [25] "TOLERANCIA      -%    95.0"                                                                                                               
#> [26] "TAXA DE DESCONTO-%     8.0"                                                                                                               
#> [27] "TIPO SIMUL. FINAL       1   (=0 NAO SIMULA; =1 S.SINT.; =2 S.HIST.; =3 CONSIST)"                                                          
#> [28] "IMPRESSAO DA OPER       1   (=0 SINOPSE; =1 OP. DETALHADA)"                                                                               
#> [29] "IMPRESSAO DA CONVERG.   1   (=0 CONVERGENCIA FINAL APENAS, =1 TOTAL)"                                                                     
#> [30] "INTERVALO P/ GRAVAR     1   SERIES SIMULADAS ( 40  SERIES GRAVADAS )"                                                                     
#> [31] "No. MIN. ITER.         30"                                                                                                                
#> [32] "RACIONAMENTO PREVENT.   0   (=0 NAO CONSIDERA NA SIMULACAO FINAL; 1=CONSIDERA)"                                                           
#> [33] "No. ANOS MANUT.UTE'S    0   (=0 NAO CONSIDERA, =1 ANO, =2 ANOS)"                                                                          
#> [34] "TENDENCIA HIDROLOGICA   0    0 (=0 NAO CONSIDERA, =1 CONSIDERA POR SUB, =2 CONSIDERA POR POSTO, NA POLITICA)  (IDEM PARA SIMULACAO FINAL)"
#> [35] "RESTRICAO DE ITAIPU     0   (FLAG DESATIVADO)"                                                                                            
#> [36] "BID                     0   (FUNCAO NAO DISPONIVEL)"                                                                                      
#> [37] "PERDAS POR TRANSMISAO   0   (=0 NAO CONSIDERA, =1 CONSIDERA)"                                                                             
#> [38] "EL NINO                 0   (FUNCAO NAO DISPONIVEL)"                                                                                      
#> [39] "ENSO INDEX              0   (FUNCAO NAO IMPLEMENTADA)"                                                                                    
#> [40] "DURACAO DO PATAMAR      1   (=0 SAZONAL, =1 VARIAVEL POR ANO)"                                                                            
#> [41] "OUTROS USOS DA AGUA     1   (=0 NAO CONSIDERA; =1 CONSIDERA)"                                                                             
#> [42] "CORRECAO DESVIO         1   (=0 CONSTANTE; =1 VARIAVEL COM O ARMAZENAMENTO)"                                                              
#> [43] "C.AVERSAO/PENAL.VMINT   1   (=0 NAO USA; =1 CAR; =2 PEN.VMINT)"                                                                           
#> [44] "TIPO DE GERA\xc7\xc3O ENAS    0   (=0 RUIDOS FW SORTEAOS DA BW E COMPENSA\xc7\xc3O CORREL.ESPACIAL; 1=COMPENS.BW; 2=COMPENS.BW E FW)"     
#> [45] "RISCO DE DEFICIT     1.00  05.00"                                                                                                         
#> [46] "PSEUDO PARTIDA QUENTE   0"                                                                                                                
#> [47] "AGRUPAMENTO LIVRE INT   0"                                                                                                                
#> [48] "EQUALIZACAO PEN INTER   1"                                                                                                                
#> [49] "REPRES.SUBMOTORIZACAO   0"                                                                                                                
#> [50] "ORDENACAO AUTOMATICA    0   (0 = NAO CONSIDERA, 1 = CONSIDERA)"                                                                           
#> [51] "CONS. CARGA ADICIONAL   0   (0 = NAO CONSIDERA, 1 = CONSIDERA)"                                                                           
#> [52] "DELTA ZSUP             10   (PERCENTUAL DE ZSUP)"                                                                                         
#> [53] "DELTA ZINF            0.2   (PERCENTUAL DE ZINF)"                                                                                         
#> [54] "ITERACOES DELTA ZINF    3   "                                                                                                             
#> [55] "DESP. ANTEC.  GNL       1   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
#> [56] "MODIF.AUTOM.ADTERM      0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
#> [57] "CONSIDERA GHMIN         0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
#> [58] "S.F. COM DATA           0"                                                                                                                
#> [59] "GER.PLs E NV1 E NV2     0    0    0    0    0    (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                       
#> [60] "SAR                     0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
#> [61] "CVAR                    1   (=0 NAO CONSIDERA , =1 CONSIDERA CTE, =2 CONSIDERA VARIAVEL)"                                                 
#> [62] "CONS. ZSUP MIN. CONV.   0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
#> [63] "DESCONSIDERA VAZMIN     0   (=0 NAO , =1 SIM)"                                                                                            
#> [64] "RESTRICOES ELETRICAS    0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
#> [65] "SELECAO DE CORTES       1   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
#> [66] "JANELA DE CORTES        0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
#> [67] "REAMOST. CENARIOS    0001 0001 0001    (UTILIZA REAMOSTRAGEM: =0 NAO; =1 SIM     TIPO: =0 RECOMB; =1 PLENA     PASSO: 0 - 45 )"           
#> [68] "CONVERGE NO ZERO        0   (=0 CONVERGENCIA TRADICIONAL, =1 CONVERGENCIA CALCULADA NO ZERO)"                                             
#> [69] "CONSULTA FCF            0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
#> [70] "IMPRESSAO ENA        0000   (=0 NAO IMPRIME , =1 IMPRIME)"                                                                                
#> [71] "IMP. CATIVO S.FINAL  0000   (=0 NAO IMPRIME , =1 IMPRIME)"                                                                                
#> [72] "REP. AGREGACAO       0001   (=0 MAIS PROXIMO, =1 CENTROIDE)"                                                                              
#> [73] "MATRIZ CORR.ESPACIAL 0001   (=0 ANUAL, =1 MENSAL)"                                                                                        
#> [74] "DESCONS. CONV. ESTAT 0001   (=0 NAO, =1 SIM)"                                                                                             
#> [75] "MOMENTO REAMOSTRAGEM    1   (=0 BACKWARD, =1 FORWARD)"                                                                                    
#> [76] "ARQUIVOS ENA         0000   (=0 APAGA APOS EXECUCAO, =1 MANTEM)"                                                                          
#> [77] "INICIO TESTE CONVERG.   1   (=0 PRIMEIRA ITERACAO, =1 ITERACAO MINIMA)"                                                                   
#> [78] "SAZ. VMINT PER. EST.    1   (=0 PRE E POS NAO SAZONAIS, =1 PRE E POS SAZONAIS)"                                                           
#> [79] "SAZ. VMAXT PER. EST.    1   (=0 PRE E POS NAO SAZONAIS, =1 PRE E POS SAZONAIS)"                                                           
#> [80] "SAZ. VMINP PER. EST.    1   (=0 PRE E POS NAO SAZONAIS, =1 PRE E POS SAZONAIS)"                                                           
#> [81] "SAZ. CFUGA E CMONT      1   (=0 PRE E POS NAO SAZONAIS, =1 PRE E POS SAZONAIS)"                                                           
#> [82] "REST. EMISSAO GEE       0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
#> [83] "INCERTEZA GER.EOLICA    0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
#> [84] "INCERTEZA GER.SOLAR     0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
#> [85] "REPRESENTACAO INCERT    0   (=1 HISTORICO, =2 PARAMETROS DA DISTRIBUICAO, =3 CENARIOS)"                                                   
#> [86] "REST. FORNEC. GAS       0   (=0 NAO CONSIDERA , =1 CONSIDERA)"
```

<sup>Created on 2021-09-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by saulo1305** [comment] 2021-09-08 11:55
Do you think it can be a path issue? Tried to move the file to a different folder and it worked, but in its original path I'm still getting the error:

`> readr::read_lines("X:\\SGE-Projetos\\02-Estudos\\03-Leilões de energia\\Leilões 2021\\0-CasoBase\\01-Casos\\Caso02c\\Caso07\\dger.eas")
Files must end with a newline
character(0)`

`> readr::read_lines("C:\\Arquivos Locais\\dger.eas")
 [1] "NEWAVE 27 - CASO BASE GARANTIA FISICA LEN A-5/2021"                                                                                       
 [2] "TIPO DE EXECUCAO        1   (=1 RODADA COMPLETA; =0 SO SIM. FINAL)"                                                                       
 [3] "DURACAO DO PERIODO      1"                                                                                                                
 [4] "No. DE ANOS DO ESTUDO   5"                                                                                                                
 [5] "MES INICIO PRE-ESTUDO  01"                                                                                                                
 [6] "MES INICIO DO ESTUDO   01"                                                                                                                
 [7] "ANO INICIO DO ESTUDO 2026"                                                                                                                
 [8] "No. DE ANOS PRE        10"                                                                                                                
 [9] "No. DE ANOS POS         5"                                                                                                                
[10] "No. DE ANOS POS FINAL   5"                                                                                                                
[11] "IMPRIME DADOS           1"                                                                                                                
[12] "IMPRIME MERCADOS        1"                                                                                                                
[13] "IMPRIME ENERGIAS        1"                                                                                                                
[14] "IMPRIME M. ESTOCAS      1"                                                                                                                
[15] "IMPRIME SUBSISTEMA      1"                                                                                                                
[16] "No MAX. DE ITER.       45"                                                                                                                
[17] "No DE SIM. FORWARD    200"                                                                                                                
[18] "No DE ABERTURAS        20 0000                (2o CAMPO: ABERTURA VARIAVEL /  =0 NAO CONSIDERA; =1 CONSIDERA)"                            
[19] "No DE SERIES SINT.   2000"                                                                                                                
[20] "ORDEM MAX. PAR(P)       6"                                                                                                                
[21] "ANO INICIAL HIST.    1931   1"                                                                                                            
[22] "CALCULA VOL.INICIAL     0   0=USA REG 20 ; 1= CALCULA EARM. INICIAL"                                                                      
[23] "VOLUME INICIAL  -%   XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X  XXX.X"             
[24] " POR REE             100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0  100.0"             
[25] "TOLERANCIA      -%    95.0"                                                                                                               
[26] "TAXA DE DESCONTO-%     8.0"                                                                                                               
[27] "TIPO SIMUL. FINAL       1   (=0 NAO SIMULA; =1 S.SINT.; =2 S.HIST.; =3 CONSIST)"                                                          
[28] "IMPRESSAO DA OPER       1   (=0 SINOPSE; =1 OP. DETALHADA)"                                                                               
[29] "IMPRESSAO DA CONVERG.   1   (=0 CONVERGENCIA FINAL APENAS, =1 TOTAL)"                                                                     
[30] "INTERVALO P/ GRAVAR     1   SERIES SIMULADAS ( 40  SERIES GRAVADAS )"                                                                     
[31] "No. MIN. ITER.         30"                                                                                                                
[32] "RACIONAMENTO PREVENT.   0   (=0 NAO CONSIDERA NA SIMULACAO FINAL; 1=CONSIDERA)"                                                           
[33] "No. ANOS MANUT.UTE'S    0   (=0 NAO CONSIDERA, =1 ANO, =2 ANOS)"                                                                          
[34] "TENDENCIA HIDROLOGICA   0    0 (=0 NAO CONSIDERA, =1 CONSIDERA POR SUB, =2 CONSIDERA POR POSTO, NA POLITICA)  (IDEM PARA SIMULACAO FINAL)"
[35] "RESTRICAO DE ITAIPU     0   (FLAG DESATIVADO)"                                                                                            
[36] "BID                     0   (FUNCAO NAO DISPONIVEL)"                                                                                      
[37] "PERDAS POR TRANSMISAO   0   (=0 NAO CONSIDERA, =1 CONSIDERA)"                                                                             
[38] "EL NINO                 0   (FUNCAO NAO DISPONIVEL)"                                                                                      
[39] "ENSO INDEX              0   (FUNCAO NAO IMPLEMENTADA)"                                                                                    
[40] "DURACAO DO PATAMAR      1   (=0 SAZONAL, =1 VARIAVEL POR ANO)"                                                                            
[41] "OUTROS USOS DA AGUA     1   (=0 NAO CONSIDERA; =1 CONSIDERA)"                                                                             
[42] "CORRECAO DESVIO         1   (=0 CONSTANTE; =1 VARIAVEL COM O ARMAZENAMENTO)"                                                              
[43] "C.AVERSAO/PENAL.VMINT   1   (=0 NAO USA; =1 CAR; =2 PEN.VMINT)"                                                                           
[44] "TIPO DE GERA\xc7\xc3O ENAS    0   (=0 RUIDOS FW SORTEAOS DA BW E COMPENSA\xc7\xc3O CORREL.ESPACIAL; 1=COMPENS.BW; 2=COMPENS.BW E FW)"     
[45] "RISCO DE DEFICIT     1.00  05.00"                                                                                                         
[46] "PSEUDO PARTIDA QUENTE   0"                                                                                                                
[47] "AGRUPAMENTO LIVRE INT   0"                                                                                                                
[48] "EQUALIZACAO PEN INTER   1"                                                                                                                
[49] "REPRES.SUBMOTORIZACAO   0"                                                                                                                
[50] "ORDENACAO AUTOMATICA    0   (0 = NAO CONSIDERA, 1 = CONSIDERA)"                                                                           
[51] "CONS. CARGA ADICIONAL   0   (0 = NAO CONSIDERA, 1 = CONSIDERA)"                                                                           
[52] "DELTA ZSUP             10   (PERCENTUAL DE ZSUP)"                                                                                         
[53] "DELTA ZINF            0.2   (PERCENTUAL DE ZINF)"                                                                                         
[54] "ITERACOES DELTA ZINF    3   "                                                                                                             
[55] "DESP. ANTEC.  GNL       1   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
[56] "MODIF.AUTOM.ADTERM      0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
[57] "CONSIDERA GHMIN         0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
[58] "S.F. COM DATA           0"                                                                                                                
[59] "GER.PLs E NV1 E NV2     0    0    0    0    0    (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                       
[60] "SAR                     0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
[61] "CVAR                    1   (=0 NAO CONSIDERA , =1 CONSIDERA CTE, =2 CONSIDERA VARIAVEL)"                                                 
[62] "CONS. ZSUP MIN. CONV.   0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
[63] "DESCONSIDERA VAZMIN     0   (=0 NAO , =1 SIM)"                                                                                            
[64] "RESTRICOES ELETRICAS    0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
[65] "SELECAO DE CORTES       1   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
[66] "JANELA DE CORTES        0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
[67] "REAMOST. CENARIOS    0001 0001 0001    (UTILIZA REAMOSTRAGEM: =0 NAO; =1 SIM     TIPO: =0 RECOMB; =1 PLENA     PASSO: 0 - 45 )"           
[68] "CONVERGE NO ZERO        0   (=0 CONVERGENCIA TRADICIONAL, =1 CONVERGENCIA CALCULADA NO ZERO)"                                             
[69] "CONSULTA FCF            0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
[70] "IMPRESSAO ENA        0000   (=0 NAO IMPRIME , =1 IMPRIME)"                                                                                
[71] "IMP. CATIVO S.FINAL  0000   (=0 NAO IMPRIME , =1 IMPRIME)"                                                                                
[72] "REP. AGREGACAO       0001   (=0 MAIS PROXIMO, =1 CENTROIDE)"                                                                              
[73] "MATRIZ CORR.ESPACIAL 0001   (=0 ANUAL, =1 MENSAL)"                                                                                        
[74] "DESCONS. CONV. ESTAT 0001   (=0 NAO, =1 SIM)"                                                                                             
[75] "MOMENTO REAMOSTRAGEM    1   (=0 BACKWARD, =1 FORWARD)"                                                                                    
[76] "ARQUIVOS ENA         0000   (=0 APAGA APOS EXECUCAO, =1 MANTEM)"                                                                          
[77] "INICIO TESTE CONVERG.   1   (=0 PRIMEIRA ITERACAO, =1 ITERACAO MINIMA)"                                                                   
[78] "SAZ. VMINT PER. EST.    1   (=0 PRE E POS NAO SAZONAIS, =1 PRE E POS SAZONAIS)"                                                           
[79] "SAZ. VMAXT PER. EST.    1   (=0 PRE E POS NAO SAZONAIS, =1 PRE E POS SAZONAIS)"                                                           
[80] "SAZ. VMINP PER. EST.    1   (=0 PRE E POS NAO SAZONAIS, =1 PRE E POS SAZONAIS)"                                                           
[81] "SAZ. CFUGA E CMONT      1   (=0 PRE E POS NAO SAZONAIS, =1 PRE E POS SAZONAIS)"                                                           
[82] "REST. EMISSAO GEE       0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
[83] "INCERTEZA GER.EOLICA    0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
[84] "INCERTEZA GER.SOLAR     0   (=0 NAO CONSIDERA , =1 CONSIDERA)"                                                                            
[85] "REPRESENTACAO INCERT    0   (=1 HISTORICO, =2 PARAMETROS DA DISTRIBUICAO, =3 CENARIOS)"                                                   
[86] "REST. FORNEC. GAS       0   (=0 NAO CONSIDERA , =1 CONSIDERA)"`

**Comment by jimhester** [comment] 2021-09-22 17:47
Possible it is an issue related to using a network drive, or possibly the unicode characters on the path.

Unfortunately I cannot investigate further until I can reproduce the issue, so I will close this for now. We can re-open it if we can manage to get a reproducible example.

**Closed by jimhester** 2021-09-22 17:47 UTC
Labels: reprex

**Comment by saulo1305** [comment] 2021-09-27 16:34
I ran a couple of tests, and the problem seems to be the unicode characters on the path. Since the file upload function at github removes the special characters when creating the link, I can't give you a reproductible example, but maybe you can create one on your own.
