### ISSUE TITLE
Problem with options(readr.show_col_types = FALSE)

### ISSUE THREAD

**Issue by lukeholman** [tidyverse/readr#1250] opened 2021-07-28 09:43 UTC
Hi there,

The option `options(readr.show_col_types = FALSE)` does not currently work for me, as shown below. When I pass `show_col_types = FALSE` directly to `read_csv()`, it works fine. Session info below. 

```r
> library(readr)
> options(readr.show_col_types = FALSE)
> read_csv("data/my_dat.csv")
Rows: 165928 Columns: 7                                                                                                                                                               
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (5): Trait, Sex, Trait guild, Trait description, Reference
dbl (2): line, trait_value


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
# A tibble: 165,928 x 7
  SNIPPED DATA
# … with 165,918 more rows
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readr_2.0.0     workflowr_1.6.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     rstudioapi_0.11  knitr_1.32       magrittr_2.0.1   hms_0.5.3        tidyselect_1.1.0 bit_1.1-15.2     R6_2.4.1        
 [9] rlang_0.4.6      fansi_0.4.1      tools_4.0.3      parallel_4.0.3   vroom_1.5.3      xfun_0.22        utf8_1.1.4       cli_2.0.2       
[17] withr_2.2.0      htmltools_0.5.0  ellipsis_0.3.1   assertthat_0.2.1 bit64_0.9-7      yaml_2.2.1       digest_0.6.25    tibble_3.0.1    
[25] lifecycle_0.2.0  crayon_1.3.4     purrr_0.3.4      later_1.0.0      tzdb_0.1.2       vctrs_0.3.0      promises_1.1.0   fs_1.4.1        
[33] glue_1.4.2       evaluate_0.14    rmarkdown_2.5    compiler_4.0.3   pillar_1.4.4     httpuv_1.5.3.1   pkgconfig_2.0.3 
```

**Comment by jimhester** [comment] 2021-07-28 13:12
Thank you for opening the issue with a reproducible example!

This is happening because the option is actually called `readr.show_types` in the code 🙈

https://github.com/tidyverse/readr/blob/3c46de143813af5e5c6c9d9839833858eb80e7cc/R/utils.R#L35

I now think it makes more sense to name option this the same as the argument name, and that is what is in the documentation elsewhere, so this is now fixed to work how you were expecting.

``` r
library(readr)
options(readr.show_col_types = FALSE)
read_csv(readr_example("mtcars.csv"))
#> # A tibble: 32 × 11
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4
#> # … with 22 more rows
```

**Closed by jimhester** 2021-07-28 13:12 UTC

**Comment by PStaus** [comment] 2022-08-26 08:08
Hi thank you for this hint and the wonderful package. Actually, it doesn't work for me now if I use 
`options(readr.show_types = FALSE)`. Only if I use `options(readr.show_col_types = FALSE)` it worked for me now. 
I am using it in an R notebook, readr Version 2.1.2. R.version 4.2.1 The autocomplete function of R Studio 2022.7.1.554 only suggests the readr.show_types option. 

```
---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
options(readr.show_types = FALSE)

read_csv(readr_example("mtcars.csv"))
```
```

Best wishes,

**Comment by daattali** [comment] 2022-09-12 21:59
I can confirm that for me too `options(readr.show_col_types = FALSE)` and `show_cols` does not
