### ISSUE TITLE
Fatal error when parsing date with %

### ISSUE THREAD

**Issue by peterdesmet** [tidyverse/readr#1229] opened 2021-07-14 09:01 UTC
R `strptime()` [documents that](https://rdrr.io/r/base/strptime.html) `%` in date/time/datetime can be escaped as `%%`: 

> Any character in the format string not part of a conversion specification is interpreted literally (and %% gives %).

This works indeed:

```R
strptime("2011-01-03%", format = "%Y-%m-%d%%")
```

The Python implementation suggests the same (last element of table at https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior).

But trying this in `readr::parse_date()` gives a **fatal error**:

```r
library(readr)
parse_date("2011-01-03%", format = "%Y-%m-%d%%")
```

Granted, readr [doesn't claim to support this escape](https://readr.tidyverse.org/reference/parse_datetime.html), but given that it seems to be a standard elsewhere, it would probably be good to handle it. 😄

**Comment by jimhester** [comment] 2021-07-14 12:44
This is a duplicate of https://github.com/tidyverse/readr/issues/1151 and https://github.com/tidyverse/readr/issues/1182, it is already fixed in the development version of readr.

**Closed by jimhester** 2021-07-14 12:44 UTC
