### ISSUE TITLE
na parameter for read_tsv not working

### ISSUE THREAD

**Issue by thackl** [tidyverse/readr#1279] opened 2021-08-20 10:33 UTC
I'm trying to parse data with missing values represented by ".". However, while `read_csv(na=".")` works as expected,  `read_tsv(`na=".")` seems to have no effect.

```r
library(readr)
d0 <- read_csv("x,y\n1,2\n3,.", na=".")
#> Rows: 2 Columns: 2
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> dbl (2): x, y
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
d0
#> # A tibble: 2 x 2
#>       x     y
#>   <dbl> <dbl>
#> 1     1     2
#> 2     3    NA

d1 <- read_tsv("x\ty\n1\t2\n3\t.\n", na=".")
#> Rows: 2 Columns: 2
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: "\t"
#> chr (1): y
#> dbl (1): x
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
d1
#> # A tibble: 2 x 2
#>       x y    
#>   <dbl> <chr>
#> 1     1 2    
#> 2     3 .
```

**Comment by jimhester** [comment] 2021-08-20 15:09
This is a duplicate of https://github.com/tidyverse/readr/issues/1258

**Closed by jimhester** 2021-08-20 15:09 UTC

**Comment by thackl** [comment] 2021-08-20 17:55
Damn, sorry, obviously forgot to check closed issues...
