### ISSUE TITLE
`read.delim` can read from process substitution handle but `read_tsv` can not

### ISSUE THREAD

**Issue by holgerbrandl** [tidyverse/readr#408] opened 2016-05-17 12:20 UTC
I'd like to read a table from a process substitution handle provided as argument

```
echo "test" > test.tsv
R --args <(cat test.tsv)
```

However when using readr this fails. Most likely because readr will jump back in forth in the file. However, also the recommended stackoverflow solution to fix the same issue for `read.csv` fails for `read_tsv`

```
inputFile <- commandArgs(T)[1]
require(readr)

## does not work (most likely because random access when parsing file)
#read_tsv(inputFile)
# > Error: Cannot read file /dev/fd/63


#try solution from http://stackoverflow.com/questions/15784373/process-substitution
OpenRead <- function(arg) {

    if (arg %in% c("-", "/dev/stdin")) {
        file("stdin", open = "r")
    } else if (grepl("^/dev/fd/", arg)) {
        fifo(arg, open = "r")
    } else {
        file(arg, open = "r")
    }
}

fileHandle <- OpenRead(inputFile)


#readLines(inputFile) ## does not work either
#readLines(fileHandle) ## works

## does also not work
#read_tsv(fileHandle)
# > Error: can only read from a binary connection

#read.delim(inputFile, header=F) ## also does not work directly...

## ...but works as expected when using connection handle:
read.delim(fileHandle, header=F)
```

Somehow `readr` seems to consider the connection as a binary stream even if it's just a plain text file handle.

**Comment by hadley** [comment] 2016-06-01 20:46
I think the problem is:

```R
commandArgs(trailingOnly = TRUE)[[1]]
# > [1] "/dev/fd/63"
```

How is readr supposed to know that's a file handle and not a regular string?

This seems out of scope for readr to me.

**Comment by holgerbrandl** [comment] 2016-06-01 21:05
According to the docs `readr` considers the file argument as literal data *only* if:
>  It must contain at least one new line to be recognised as data (instead of a path).

(see ?read_tsv). So process substituation inputs  like `/dev/fd/63` should be detected as path since they do not contain any newline character.

**Comment by kenahoo** [comment] 2016-11-14 19:04
@hadley I think you misunderstood what @holgerbrandl was saying - he wants `/dev/fd/63` to be read like any normal path, not to get special treatment of some kind.  I see no reason why paths in `/dev/fd` shouldn't be supported just like any other path on the filesystem.

**Comment by holgerbrandl** [comment] 2016-11-14 19:09
Indeed @kenahoo this was my intention when creating the ticket.

**Comment by hadley** [comment] 2016-11-14 19:13
In that case, please provide a reproducible example

**Comment by kenahoo** [comment] 2016-11-14 21:25
@holgerbrandl It looks like both `read.delim` and `read_tsv` will work properly if instead of reading from `commandArgs(TRUE)[1]`, you read from `file(commandArgs(TRUE)[1], raw=TRUE)`.

```
% echo "x\ty\n3\t4\n5\t6\n" > test.tsv; Rscript -e 'read.delim(file(commandArgs(TRUE)[1], raw=TRUE))' <(cat test.tsv) 
  x y
1 3 4
2 5 6

% Rscript -e 'library(readr); read_tsv(file(commandArgs(TRUE)[1], raw=TRUE))' <(cat test.tsv)
Parsed with column specification:
cols(
  x = col_integer(),
  y = col_integer()
)
# A tibble: 2 × 2
      x     y
  <int> <int>
1     3     4
2     5     6
```

I do think it's unfortunate that the script would have to know when to wrap in `file(... raw=TRUE)` and when not to, but I think that's often a problem in R when reading from non-regular files.

**Comment by kenahoo** [comment] 2016-11-14 21:26
If the @tidyverse were feeling generous, it could sense a `/dev/fd/` file and wrap it for you, but that might be going too far.

**Closed** 2016-12-22 19:36 UTC

**Comment by sjackman** [comment] 2017-03-29 17:30
I've just run into this bug myself. The following test fails when the operating system is macOS and the file system is HFS. It succeeds on macOS when the file system is NFS. It succeeds on Linux regardless of file system.

```
❯❯❯ printf "a,b,c\n1,2,3\n" >file.tsv
❯❯❯ Rscript --default-packages=tidyverse -e 'read_tsv("/dev/stdin")' <file.tsv
Error: '/dev/fd/file.tsv' does not exist.
```

On macOS with HFS, I'm guessing that R is using the `fcntl(fd, F_GETPATH)` system call to convert the standard input file descriptor `0` to a file name, and it's bungling it.
See http://stackoverflow.com/a/13544447/423153

# Summary and workaround

| OS   | FS   | 😶   |
| ---- | ---- | ---- |
| 🐧   | ✱     | 😃   |
| 🍎   | ☁️   | 😃   |
| 🍎   | 💾   | 😖   |

```
❯❯❯ Rscript --default-packages=tidyverse -e 'read_tsv("/dev/stdin")' <file.tsv
😖 Error: '/dev/fd/file.tsv' does not exist.
❯❯❯ Rscript --default-packages=tidyverse -e 'read_tsv("/dev/fd/0")' <file.tsv
😖 Error: '/dev/fd/file.tsv' does not exist.
❯❯❯ Rscript --default-packages=tidyverse -e 'read_tsv(file("/dev/stdin"))' <file.tsv
😖 # A tibble: 0 × 0
❯❯❯ cat file.tsv | Rscript --default-packages=tidyverse -e 'read_tsv("/dev/stdin")'
😖 Error: Cannot read file /dev/fd/0: Invalid argument
❯❯❯ Rscript --default-packages=tidyverse -e 'read_tsv(file("/dev/stdin", "rb"))' <file.tsv
😃
❯❯❯ Rscript --default-packages=tidyverse -e 'read_tsv(file("/dev/fd/0", "rb"))' <file.tsv
😃
❯❯❯ Rscript --default-packages=tidyverse -e 'read_tsv(file("stdin"))' <file.tsv
😃
```

**Comment by jimhester** [comment] 2017-03-31 15:09
I think `readr::read_tsv(file("stdin"))` is going to be the most portable way read from standard input.
