### ISSUE TITLE
Error in open.connection(con, "rb") while reading from internet.

### ISSUE THREAD

**Issue by Abhijitsj** [tidyverse/readr#769] opened 2017-12-28 08:04 UTC
```r
ext_tracks_file <- paste0("http://rammb.cira.colostate.edu/research/",
                          "tropical_cyclones/tc_extended_best_track_dataset/",
                          "data/ebtrk_atlc_1988_2015.txt")

library(readr)

# Create a vector of the width of each column
ext_tracks_widths <- c(7, 10, 2, 2, 3, 5, 5, 6, 4, 5, 4, 4, 5, 3, 4, 3, 3, 3,
                       4, 3, 3, 3, 4, 3, 3, 3, 2, 6, 1)

# Create a vector of column names, based on the online documentation for this data
ext_tracks_colnames <- c("storm_id", "storm_name", "month", "day",
                          "hour", "year", "latitude", "longitude",
                          "max_wind", "min_pressure", "rad_max_wind",
                          "eye_diameter", "pressure_1", "pressure_2",
                          paste("radius_34", c("ne", "se", "sw", "nw"), sep = "_"),
                          paste("radius_50", c("ne", "se", "sw", "nw"), sep = "_"),
                          paste("radius_64", c("ne", "se", "sw", "nw"), sep = "_"),
                          "storm_type", "distance_to_land", "final")

# Read the file in from its url
ext_tracks <- read_fwf(getURL(ext_tracks_file), 
                       fwf_widths(ext_tracks_widths, ext_tracks_colnames),
                       na = "-99")
```
Then I get below error:
```
Error in open.connection(con, "rb") : 
  Failed to connect to rammb.cira.colostate.edu port 80: Connection refused
```
I am getting above error, please guide.

**Comment by cderv** [comment] 2017-12-28 08:23
Can you provide a [reprex](http://reprex.tidyverse.org/) to help us help you? 

First advice : 
+ Edit your issue to work on the formatting. It is not helpful right now. Issues in Github are written using markdown. Looks [here](https://guides.github.com/features/mastering-markdown/) if you are new to it.
+ Provides with an example we can reproduce. Here, your issue is with the connexion, not the parsing so it is something to do with reading the file `ext_tracks_file` that we do not have. You can attach a sample in the github issue by drag & drop or by copy paste. 

Thanks!

**Comment by Abhijitsj** [comment] 2017-12-28 08:37
ext_tracks_file <- paste0("http://rammb.cira.colostate.edu/research/",
                          "tropical_cyclones/tc_extended_best_track_dataset/",
                          "data/ebtrk_atlc_1988_2015.txt")

I will try reprex, for now please consider above information.

**Comment by Abhijitsj** [comment] 2017-12-28 08:54
Also, I installed reprex but receiving below error,

library(reprex)
Error in file(file, "rt") : invalid 'description' argument
In addition: Warning message:
package ‘reprex’ was built under R version 3.4.3 
Error: package or namespace load failed for ‘reprex’:
 unable to load R code in package ‘knitr’

**Comment by cderv** [comment] 2017-12-28 10:30
Thank you. In your example, what is `getURL` ? It seems the issue comes from there. 
With `readr` I do not need this function (and it is not base R I think). 

``` r
ext_tracks_file <- file.path("http://rammb.cira.colostate.edu/research",
                          "tropical_cyclones/tc_extended_best_track_dataset",
                          "data/ebtrk_atlc_1988_2015.txt")

library(readr)

ext_tracks_widths <- c(7, 10, 2, 2, 3, 5, 5, 6, 4, 5, 4, 4, 5, 3, 4, 3, 3, 3,
                       4, 3, 3, 3, 4, 3, 3, 3, 2, 6, 1)

ext_tracks_colnames <- c("storm_id", "storm_name", "month", "day",
                         "hour", "year", "latitude", "longitude",
                         "max_wind", "min_pressure", "rad_max_wind",
                         "eye_diameter", "pressure_1", "pressure_2",
                         paste("radius_34", c("ne", "se", "sw", "nw"), sep = ""),
                         paste("radius_50", c("ne", "se", "sw", "nw"), sep = ""),
                         paste("radius_64", c("ne", "se", "sw", "nw"), sep = "_"),
                         "storm_type", "distance_to_land", "final")

ext_tracks <- read_fwf(ext_tracks_file,
                       fwf_widths(ext_tracks_widths, ext_tracks_colnames),
                       na = "-99")
#> Parsed with column specification:
#> cols(
#>   .default = col_integer(),
#>   storm_id = col_character(),
#>   storm_name = col_character(),
#>   month = col_character(),
#>   day = col_character(),
#>   hour = col_character(),
#>   latitude = col_double(),
#>   longitude = col_double(),
#>   storm_type = col_character(),
#>   final = col_character()
#> )
#> See spec(...) for full column specifications.
ext_tracks
#> # A tibble: 11,824 x 29
#>    storm_id storm_name month   day  hour  year latitude longitude max_wind
#>       <chr>      <chr> <chr> <chr> <chr> <int>    <dbl>     <dbl>    <int>
#>  1   AL0188    ALBERTO    08    05    18  1988     32.0      77.5       20
#>  2   AL0188    ALBERTO    08    06    00  1988     32.8      76.2       20
#>  3   AL0188    ALBERTO    08    06    06  1988     34.0      75.2       20
#>  4   AL0188    ALBERTO    08    06    12  1988     35.2      74.6       25
#>  5   AL0188    ALBERTO    08    06    18  1988     37.0      73.5       25
#>  6   AL0188    ALBERTO    08    07    00  1988     38.7      72.4       25
#>  7   AL0188    ALBERTO    08    07    06  1988     40.0      70.8       30
#>  8   AL0188    ALBERTO    08    07    12  1988     41.5      69.0       35
#>  9   AL0188    ALBERTO    08    07    18  1988     43.0      67.5       35
#> 10   AL0188    ALBERTO    08    08    00  1988     45.0      65.5       35
#> # ... with 11,814 more rows, and 20 more variables: min_pressure <int>,
#> #   rad_max_wind <int>, eye_diameter <int>, pressure_1 <int>,
#> #   pressure_2 <int>, radius_34ne <int>, radius_34se <int>,
#> #   radius_34sw <int>, radius_34nw <int>, radius_50ne <int>,
#> #   radius_50se <int>, radius_50sw <int>, radius_50nw <int>,
#> #   radius_64_ne <int>, radius_64_se <int>, radius_64_sw <int>,
#> #   radius_64_nw <int>, storm_type <chr>, distance_to_land <int>,
#> #   final <chr>
```

Created on 2017-12-28 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

Another advice: when you are not sure it is an issue with the package but just need some help or advice with you code to figure it out, please also consider [community.rstudio.com](https://community.rstudio.com/) or [StackOverflow](https://stackoverflow.com/questions/tagged/r). There is better chance that the community can help you there.

**Comment by Abhijitsj** [comment] 2017-12-29 08:06
Thanks, however i was just trying something so I used getURL but if I use url function or no function there. Still the error is there. Anyway as you suggested I will post this on R community as well.

**Comment by batpigandme** [comment] 2017-12-29 12:26
@Abhijitsj You say _Still the error is there._, could you please make a reprex, since @cderv seems to have been able to run the code without an error?

**Comment by cderv** [comment] 2017-12-29 18:26
For reference, and following the subject, the question was ask on [community.rstudio.com](https://community.rstudio.com/t/error-in-open-connection-con-rb/3850)

**Comment by batpigandme** [comment] 2017-12-29 18:55
As other community members have run the same code successfully, I'll close the issue here.

**Closed by batpigandme** 2017-12-29 18:55 UTC
Labels: reprex
