### ISSUE TITLE
Problems with upgrade to read v2.0

### ISSUE THREAD

**Issue by pschloss** [tidyverse/readr#1252] opened 2021-07-29 18:32 UTC
With the upgrade to v2.0 there is now a dependency on `vroom`, which can't handle `\r` line endings. Previously, this wasn't a problem for `read_csv`, but it is now as outlined in https://github.com/r-lib/vroom/issues/360. Since the odds are small of me getting sites that post data with `\r` line endings to change them, is there a way for `readr` to maintain backwards compatibility?

```R
$ read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/comma-survey/comma-survey.csv")
Error: The size of the connection buffer (262144) was not large enough
to fit a complete line:
  * Increase it by setting `Sys.setenv("VROOM_CONNECTION_SIZE")`
```

**Comment by jimhester** [comment] 2021-07-29 18:59
As mentioned in the [NEWS](https://github.com/tidyverse/readr/blob/master/NEWS.md#second-edition-changes) you can revert back to the first edition parser with `with_edition(1, ...)`.

``` r
library(readr)
with_edition(1, read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/comma-survey/comma-survey.csv"))
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   RespondentID = col_double(),
#>   `In your opinion, which sentence is more gramatically correct?` = col_character(),
#>   `Prior to reading about it above, had you heard of the serial (or Oxford) comma?` = col_character(),
#>   `How much, if at all, do you care about the use (or lack thereof) of the serial (or Oxford) comma in grammar?` = col_character(),
#>   `How would you write the following sentence?` = col_character(),
#>   `When faced with using the word "data", have you ever spent time considering if the word was a singular or plural noun?` = col_character(),
#>   `How much, if at all, do you care about the debate over the use of the word "data" as a singluar or plural noun?` = col_character(),
#>   `In your opinion, how important or unimportant is proper use of grammar?` = col_character(),
#>   Gender = col_character(),
#>   Age = col_character(),
#>   `Household Income` = col_character(),
#>   Education = col_character(),
#>   `Location (Census Region)` = col_character()
#> )
#> # A tibble: 1,129 × 13
#>    RespondentID `In your opinion, w… `Prior to reading ab… `How much, if at all…
#>           <dbl> <chr>                <chr>                 <chr>                
#>  1   3292953864 It's important for … Yes                   Some                 
#>  2   3292950324 It's important for … No                    Not much             
#>  3   3292942669 It's important for … Yes                   Some                 
#>  4   3292932796 It's important for … Yes                   Some                 
#>  5   3292932522 It's important for … No                    Not much             
#>  6   3292926586 It's important for … No                    A lot                
#>  7   3292908135 It's important for … Yes                   A lot                
#>  8   3292869879 It's important for … Yes                   A lot                
#>  9   3292863455 It's important for … Yes                   A lot                
#> 10   3292860428 It's important for … No                    Not at all           
#> # … with 1,119 more rows, and 9 more variables:
#> #   How would you write the following sentence? <chr>,
#> #   When faced with using the word "data", have you ever spent time considering if the word was a singular or plural noun? <chr>,
#> #   How much, if at all, do you care about the debate over the use of the word "data" as a singluar or plural noun? <chr>,
#> #   In your opinion, how important or unimportant is proper use of grammar? <chr>,
#> #   Gender <chr>, Age <chr>, Household Income <chr>, Education <chr>,
#> #   Location (Census Region) <chr>
```

<sup>Created on 2021-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jimhester** [comment] 2021-07-29 19:04
As the underlying issue is a duplicate of #1236 and https://github.com/tidyverse/readr/issues/1246 I am going to close this issue.

**Closed by jimhester** 2021-07-29 19:04 UTC
