### ISSUE TITLE
Unexpected behavior in parsing TXT file

### ISSUE THREAD

**Issue by stebif68** [tidyverse/readr#516] opened 2016-09-09 07:23 UTC
I am reading data using readr. Data is txt file where each column is separate by one (or more) columns of space.
Data has 1000 rows. If I read 996 rows, the first col is an integer. If I read 997 rows, the same first col is character. I guess there is some "special" character but I cannot figure out what's going on

[DAT44M100.txt](https://github.com/hadley/readr/files/463360/DAT44M100.txt)

DatiMorf44xxx <- read_table(file.path(dir,'DAT44M.txt'),col_names = c('id','OpDim',
                                                                 'YearSeason',
                                                                 'HerdYear',
                                                                 'age','age2',
                                                                 'v1','v2',
                                                                 'v3','v4',
                                                                 'v5','v6',
                                                                 'v7','v8'),
                            n_max=996)
cols(
  id = col_integer(),
  OpDim = col_integer(),
  YearSeason = col_integer(),
  HerdYear = col_integer(),
  age = col_integer(),
  age2 = col_integer(),
  v1 = col_integer(),
  v2 = col_integer(),
  v3 = col_integer(),
  v4 = col_integer(),
  v5 = col_integer(),
  v6 = col_integer(),
  v7 = col_integer(),
  v8 = col_integer()
)

DatiMorf44xxx <- read_table(file.path(dir,'DAT44M.txt'),col_names = c('id','OpDim',
                                                                 'YearSeason',
                                                                 'HerdYear',
                                                                 'age','age2',
                                                                 'v1','v2',
                                                                 'v3','v4',
                                                                 'v5','v6',
                                                                 'v7','v8'),
                            n_max=997)

cols(
  id = col_character(),
  OpDim = col_integer(),
  YearSeason = col_integer(),
  HerdYear = col_integer(),
  age = col_integer(),
  age2 = col_integer(),
  v1 = col_integer(),
  v2 = col_integer(),
  v3 = col_integer(),
  v4 = col_integer(),
  v5 = col_integer(),
  v6 = col_integer(),
  v7 = col_integer(),
  v8 = col_integer()
)

**Comment by hadley** [comment] 2016-12-22 19:30
Duplicate of #518

**Closed by hadley** 2016-12-22 19:30 UTC
