### ISSUE TITLE
read_csv in 2.0.0 does not support files with carriage return `\r` as the line separator

### ISSUE THREAD

**Issue by garthtarr** [tidyverse/readr#1236] opened 2021-07-21 13:12 UTC
Edition 2 doesn't seem to identify the line breaks in the example csv file provided. Normally I would assume it's an issue with the file itself, but this file works fine with edition 1 of `read_csv()` and with `read.csv()` so it may be worth investigating what's going on with edition 2 of `read_csv()`.

```r
path = "https://github.com/DATA2002/data/raw/master/Cereal.csv"
c0 = read.csv(path) # works
c1 = with_edition(1, read_csv(path))  # works
c2 = read_csv(path) # doesn't work
dim(c0)
dim(c1)
dim(c2)
```

Output:

```r
> path = "https://github.com/DATA2002/data/raw/master/Cereal.csv"
> c0 = read.csv(path)
> c0 = read.csv(path)
> c1 = with_edition(1, read_csv(path)) 

── Column specification ────────────────────────────────
cols(
  name = col_character(),
  mfr = col_character(),
  type = col_character(),
  calories = col_double(),
  protein = col_double(),
  fat = col_double(),
  sodium = col_double(),
  fiber = col_double(),
  carbo = col_double(),
  sugars = col_double(),
  potass = col_double(),
  vitamins = col_double(),
  shelf = col_double(),
  weight = col_double(),
  cups = col_double(),
  rating = col_double()
)

> c0 = read.csv(path)
> c1 = with_edition(1, read_csv(path)) 

── Column specification ────────────────────────────────
cols(
  name = col_character(),
  mfr = col_character(),
  type = col_character(),
  calories = col_double(),
  protein = col_double(),
  fat = col_double(),
  sodium = col_double(),
  fiber = col_double(),
  carbo = col_double(),
  sugars = col_double(),
  potass = col_double(),
  vitamins = col_double(),
  shelf = col_double(),
  weight = col_double(),
  cups = col_double(),
  rating = col_double()
)

> c2 = read_csv(path)
New names:
* N -> N...17
* C -> C...18
* `70` -> `70...19`
* `4` -> `4...20`
* `1` -> `1...21`
* ...
Rows: 0 Columns: 1177
── Column specification ────────────────────────────────
Delimiter: ","
chr (1177): name, mfr, type, calories, protein, fat,...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
> dim(c0)
[1] 77 16
> dim(c1)
[1] 77 16
> dim(c2)
[1]    0 1177
```

**Comment by jimhester** [comment] 2021-07-21 13:56
This file uses only carriage returns (`\r`) as line-breaks.

As mentioned in https://github.com/tidyverse/readr/blob/master/NEWS.md#deprecated-or-superseded-functions-and-features the last major OS which used the style of line breaks was 'classic' Mac OS, which had its last release in 2001. These types of files are no longer supported in the 2nd edition of readr.

You can use the `mac2unix` command line tool to convert these files before reading, or alternatively define a helper function to convert the newlines to carriage return before reading, e.g.

```r
read_delim_cr <- function(file, ...) {
  data <- read_file_raw(file)
  for (i in seq_along(data)) {
    if (data[[i]] == 0x0d) {
      data[[i]] <- as.raw(0x0a)
    }
  }
  read_delim(data, ...)
}

read_delim_cr("https://github.com/DATA2002/data/raw/master/Cereal.csv")
```

**Comment by vqv** [comment] 2021-07-29 02:45
Sorry, to reopen this issue but I ran into this with the `noc_regions.csv` file from the _120 years of Olympic history_ Kaggle data set (https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results).  Although, `\r` line breaks have not been used by a major OS since 2001, there are probably many CSV files out in the wild that use this style of line breaks.

Is there anyway to detect this and notify the user? I think one possible symptom is that the imported data will apparently have 0 rows and an enormous number of columns. I suspect that many users will not be able to easily tell from opening the CSV file (in RStudio or another text editor) that it uses `\r` as the line break character.

**Comment by jmbarbone** [comment] 2021-07-29 16:52
Additionally, `write_delim()` supports an `eol` param so it seems odd we can still create files with `\r` as a line-break but not read them.

**Comment by ercbk** [comment] 2021-08-29 20:10
I'd just like to add that people might also run into this issue with scraped html tables. I had a text column with \r\n that caused write_csv to throw an error.

**Comment by cboettig** [comment] 2021-09-08 19:33
I think this issue also breaks readr parsing of famous NOAA datasets on climate, like these records:

```r
#  returns 0 rows; same command is fine with read.csv()
read_csv("http://climate.nasa.gov/system/internal_resources/details/original/499_GRN_ANT_mass_changes.csv", skip=9)
```

Note that this is particularly difficult for many users to debug, because the separators are invisible.  In this case I think the problem is the missing carriage return on the last file.  Let me know if that should be considered a different issue?

**Comment by jimhester** [comment] 2021-09-08 19:50
Closed by https://github.com/r-lib/vroom/commit/86b12829e87e53582db647c09661258580d845d5

**Closed by jimhester** 2021-09-08 19:50 UTC
Labels: feature
