### ISSUE TITLE
Dev version of `readr` cannot read file that has non-ASCII name

### ISSUE THREAD

**Issue by niheaven** [tidyverse/readr#1214] opened 2021-06-02 10:23 UTC
Dev version of `readr` cannot read non-ASCII file name

- Use CRAN `readr` v 1.4.0

``` r
sessioninfo::package_info("readr", dependencies = FALSE)
#>  package * version date       lib source        
#>  readr     1.4.0   2020-10-05 [1] CRAN (R 4.1.0)
#> 
#> [1] E:/Documents/R/win-library/4.1
#> [2] D:/Scoop/apps/r/4.1.0/library
readr::write_lines("test", "test.txt")
readr::read_file("test.txt")
#> [1] "test\n"
file.copy("test.txt", "测试.txt", overwrite = TRUE)
#> [1] TRUE
file.exists("测试.txt")
#> [1] TRUE
readLines(file("测试.txt"))
#> [1] "test"
readr::read_file("测试.txt")
#> [1] "test\n"
```

- Use dev ver, notice error on last line

``` r
sessioninfo::package_info("readr", dependencies = FALSE)
#>  package * version    date       lib source                          
#>  readr     1.9.9.9000 2021-06-02 [1] Github (tidyverse/readr@a189e90)
#> 
#> [1] E:/Documents/R/win-library/4.1
#> [2] D:/Scoop/apps/r/4.1.0/library
readr::write_lines("test", "test.txt")
readr::read_file("test.txt")
#> [1] "test\n"
file.copy("test.txt", "测试.txt", overwrite = TRUE)
#> [1] TRUE
file.exists("测试.txt")
#> [1] TRUE
readLines(file("测试.txt"))
#> [1] "test"
readr::read_file("测试.txt")
#> Error: Cannot read file No such file or directory: h
```

**Comment by jimhester** [comment] 2021-06-02 12:20
This should be fixed, if you could install the dev version in a fresh R session and verify the fix we would appreciate it.

**Comment by jimhester** [comment] 2021-06-02 12:38
Actually I think there might be a different issue, I will try to reproduce your results on my windows machine.

Can you tell me what your current locale is? e.g. the output of `Sys.setlocale()`?

**Comment by jimhester** [comment] 2021-06-02 13:48
Ok I reproduced this and figured out the root cause, it should (really) be fixed now.

**Closed** 2021-06-02 13:47 UTC
Labels: bug

**Comment by niheaven** [comment] 2021-06-02 15:51
It is fully fixed now.

And there is one breaking change between `readr` 2.0 and 1.4 that might break working code, but I'll open another issue 😄
