### ISSUE TITLE
read_table() has strange behavior reading doubles greater than 100M

### ISSUE THREAD

**Issue by wwgordon** [tidyverse/readr#977] opened 2019-03-13 22:18 UTC
I've been trying to read in chromosomal positions with read_table(), and it seems to be ignoring the early digits for numbers greater than 100M:

``` r
library(tidyverse)
rm(list = ls())
path = "<path>"

gwas_base = read.table(path, header = TRUE)
gwas_tidy = read_table(path, col_names = TRUE)
#> Parsed with column specification:
#> cols(
#>   CHR = col_double(),
#>   SNP = col_character(),
#>   BP = col_double(),
#>   A1 = col_character(),
#>   TEST = col_character(),
#>   NMISS = col_double(),
#>   BETA = col_double(),
#>   SE = col_double(),
#>   `L95      U95` = col_character(),
#>   STAT = col_double(),
#>   P = col_double()
#> )

summary(gwas_base$BP)
#>      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
#>     36787  31568379  69147960  78449518 115057896 249202567
summary(gwas_tidy$BP)
#>     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
#>      827 18564087 38138482 42432636 65551527 99997478
dim(gwas_base)
#> [1] 207089     12
dim(gwas_tidy)
#> [1] 207089     11
gwas_base[1, ]
#>   CHR       SNP      BP A1 TEST NMISS  BETA    SE     L95   U95  STAT
#> 1   1 rs6687776 1030565  T  ADD  1700 1.701 1.243 -0.7357 4.137 1.368
#>        P
#> 1 0.1715
gwas_tidy[1, ]
#> # A tibble: 1 x 11
#>     CHR SNP       BP A1    TEST  NMISS  BETA    SE `L95      U95`  STAT
#>   <dbl> <chr>  <dbl> <chr> <chr> <dbl> <dbl> <dbl> <chr>          <dbl>
#> 1     1 rs66… 1.03e6 T     ADD    1700  1.70  1.24 -0.7357    4.…  1.37
#> # … with 1 more variable: P <dbl>
```

<sup>Created on 2019-03-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I suspect this has to do with the fact that the first few hundred positions are much smaller, but it seems like a dangerous behavior without warning.

Additionally, read_table() is treating the L95 and U95 columns as one column.

**Comment by jimhester** [comment] 2019-03-14 12:52
This is a duplicate of https://github.com/tidyverse/readr/issues/976

**Closed** 2019-03-14 12:52 UTC
