### ISSUE TITLE
What exactly does lazy do?

### ISSUE THREAD

**Issue by abalter** [tidyverse/readr#1490] opened 2023-04-04 01:17 UTC
I just read in a large csv file. I used `lazy=T`. However, the size of the object I read the file into is the same size as the file itself.

Do I need to do something else to read the table in lazily?

If I am actually able to read in a file lazily, can I use dplyr verbs on it?

```
> library(tidyverse)
> df = read_csv('mem_detail.csv', lazy=T)
Rows: 61923459 Columns: 28
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> object.size(df)
13048425864 bytes
```

```
-rw------- 1 balter  chse    12G Mar 12 19:05 mem_detail.csv
```

**Comment by hadley** [comment] 2023-07-31 21:52
Duplicate of #1499

**Closed by hadley** 2023-07-31 21:52 UTC
