### ISSUE TITLE
INF, -INF, NaN no longer parsed by col_double()

### ISSUE THREAD

**Issue by peterdesmet** [tidyverse/readr#1298] opened 2021-09-07 19:06 UTC
In readr 1.4.0, values `INF`, `-INF` and `NaN` were parsed by `col_double()`:

```r
# devtools::install_github("tidyverse/readr@v1.4.0")
library(readr)
file <- "https://gist.githubusercontent.com/peterdesmet/9525d4aaefc109230f162164e5d66e23/raw/fda84bf3b924d37b926eaf1b80b794ff0a119dca/numbers.csv"
read_csv(file, col_types = "dddd")
#> # A tibble: 3 × 4
#>     num num_nan num_inf num_ninf
#>   <dbl>   <dbl>   <dbl>    <dbl>
#> 1     3     NaN     Inf     -Inf
#> 2     3     NaN     Inf     -Inf
#> 3     3       3       3        3

read_csv(file)
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   num = col_double(),
#>   num_nan = col_double(),
#>   num_inf = col_double(),
#>   num_ninf = col_double()
#> )
#> # A tibble: 3 × 4
#>     num num_nan num_inf num_ninf
#>   <dbl>   <dbl>   <dbl>    <dbl>
#> 1     3     NaN     Inf     -Inf
#> 2     3     NaN     Inf     -Inf
#> 3     3       3       3        3
```

In readr 2.0.1 that is no longer the case. And when no column specification is provided, the columns are interpreted as characters:

``` r
library(readr)
file <- "https://gist.githubusercontent.com/peterdesmet/9525d4aaefc109230f162164e5d66e23/raw/fda84bf3b924d37b926eaf1b80b794ff0a119dca/numbers.csv"
read_csv(file, col_types = "dddd")
#> Warning: One or more parsing issues, see `problems()` for details
#> # A tibble: 3 × 4
#>     num num_nan num_inf num_ninf
#>   <dbl>   <dbl>   <dbl>    <dbl>
#> 1     3      NA      NA       NA
#> 2     3      NA      NA       NA
#> 3     3       3       3        3

read_csv(file)
#> Rows: 3 Columns: 4
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr (3): num_nan, num_inf, num_ninf
#> dbl (1): num
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> # A tibble: 3 × 4
#>     num num_nan num_inf num_ninf
#>   <dbl> <chr>   <chr>   <chr>   
#> 1     3 NaN     INF     -INF    
#> 2     3 nan     inf     -inf    
#> 3     3 3       3       3
```

Can the original behaviour be reinstated?

**Comment by jimhester** [comment] 2021-09-08 13:46
This is a duplicate of https://github.com/tidyverse/readr/issues/1283. It is fixed with the current development version of vroom and will be on CRAN in a week or so.

**Closed by jimhester** 2021-09-08 13:46 UTC
