### ISSUE TITLE
Leading whitespace causes header row duplication

### ISSUE THREAD

**Issue by tdsmith** [tidyverse/readr#747] opened 2017-11-20 18:26 UTC
Adding whitespace at the beginning of a file (or between the end of a list of comments and a header row) causes the header row to be duplicated in the data.

Compare:
No leading whitespace; gives expected result
```
> read_csv("foo,bar\n1,2")
# A tibble: 1 x 2
    foo   bar
  <int> <int>
1     1     2
```

With leading whitespace; duplicates header row (and changes column types)
```
> read_csv("\nfoo,bar\n1,2")
# A tibble: 2 x 2
    foo   bar
  <chr> <chr>
1   foo   bar
2     1     2
```

readr is version 1.1.1. Thanks!

**Comment by jimhester** [comment] 2017-12-07 21:54
I can reproduce this, looks like a bug.

**Comment by J535D165** [comment] 2017-12-07 23:05
Duplicate of #680

**Comment by jimhester** [comment] 2017-12-11 17:36
Closed by https://github.com/tidyverse/readr/commit/6517708c7863887d13c09b8265fcff75213fa15e

**Closed by jimhester** 2017-12-11 17:36 UTC
Labels: bug

**Comment by tdsmith** [comment] 2017-12-11 17:38
Awesome; thanks!
