### ISSUE TITLE
Can't read from `stdin`

### ISSUE THREAD

**Issue by kenahoo** [tidyverse/readr#551] opened 2016-11-14 19:17 UTC
In a simple test script, I can read `stdin` fine with `utils::read.table`, but not with `readr::read_table`:

```
% echo "x y\n3 4\n5 6" | Rscript -e 'read.table(file("stdin"))'                 
  V1 V2
1  x  y
2  3  4
3  5  6

% echo "x y\n3 4\n5 6" | Rscript -e 'library(readr); read_table(file("stdin"))'
Error in isOpen(con) : invalid connection
Calls: read_table ... new_datasource -> structure -> read_connection -> isOpen
Execution halted
```

Is this an inherent limitation of `readr`'s approach, or is it just overzealous checking of the handle?

**Comment by hadley** [comment] 2016-12-22 19:13
Duplicate of #552

**Closed by hadley** 2016-12-22 19:13 UTC
