### ISSUE TITLE
read_csv parsing incorrectly

### ISSUE THREAD

**Issue by stanislavzza** [tidyverse/readr#1411] opened 2022-07-12 19:51 UTC
```
library(readr)
lines <- "C1
2011D2"
read_csv(lines)
```

produces a double instead of a character, as if 2011D2 was being interpreted as an exponential notation 2011E2

```
# A tibble: 1 × 1
      C1
   <dbl>
1 201100
```

-----------------
R version 4.2.0 Patched (2022-06-03 r82452 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

other attached packages:
[1] readr_2.1.2

**Comment by dpprdan** [comment] 2023-02-07 20:41
``` r
library(readr)
read_delim(I("C1\n2011D2"))
#> Error: Could not guess the delimiter.
#> 
#> Use `vroom(delim =)` to specify one explicitly.
read_delim(I("C1\n2011D2"), delim = "")
#> Error: `delim` must be at least one character, use `read_table()` for whitespace delimited input.
read_table(I("C1\n2011D2"))
#> # A tibble: 1 × 1
#>       C1
#>    <dbl>
#> 1 201100
```

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.2 (2022-10-31 ucrt)
#>  os       Windows 10 x64 (build 19044)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language en
#>  collate  German_Germany.utf8
#>  ctype    German_Germany.utf8
#>  tz       Europe/Berlin
#>  date     2023-02-07
#>  pandoc   2.19.2 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  ! package     * version    date (UTC) lib source
#>  D archive       1.1.5      2022-05-06 [1] CRAN (R 4.2.2)
#>    bit           4.0.5      2022-11-15 [1] CRAN (R 4.2.2)
#>    bit64         4.0.5      2020-08-30 [1] CRAN (R 4.2.0)
#>    cli           3.6.0      2023-01-09 [1] CRAN (R 4.2.2)
#>    crayon        1.5.2      2022-09-29 [1] RSPM
#>    digest        0.6.31     2022-12-11 [1] CRAN (R 4.2.2)
#>    ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.2.0)
#>    evaluate      0.20       2023-01-17 [1] CRAN (R 4.2.2)
#>    fansi         1.0.4      2023-01-22 [1] CRAN (R 4.2.2)
#>    fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.2.0)
#>    fs            1.6.0      2023-01-23 [1] CRAN (R 4.2.2)
#>    glue          1.6.2.9000 2023-01-16 [1] Github (tidyverse/glue@5a16502)
#>    hms           1.1.2      2022-08-19 [1] CRAN (R 4.2.1)
#>    htmltools     0.5.4      2022-12-07 [1] CRAN (R 4.2.2)
#>    knitr         1.42       2023-01-25 [1] CRAN (R 4.2.2)
#>    lifecycle     1.0.3      2022-10-07 [1] RSPM
#>    magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.2.0)
#>    pillar        1.8.1      2022-08-19 [1] CRAN (R 4.2.1)
#>    pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.2.0)
#>    purrr         1.0.1      2023-01-10 [1] CRAN (R 4.2.2)
#>    R.cache       0.16.0     2022-07-21 [1] CRAN (R 4.2.1)
#>    R.methodsS3   1.8.2      2022-06-13 [1] CRAN (R 4.2.0)
#>    R.oo          1.25.0     2022-06-12 [1] CRAN (R 4.2.0)
#>    R.utils       2.12.2     2022-11-11 [1] CRAN (R 4.2.2)
#>    R6            2.5.1      2021-08-19 [1] CRAN (R 4.2.0)
#>    readr       * 2.1.3.9000 2023-02-07 [1] Github (tidyverse/readr@ee3fbae)
#>    reprex        2.0.2      2022-08-17 [1] CRAN (R 4.2.1)
#>    rlang         1.0.6      2022-09-24 [1] CRAN (R 4.2.1)
#>    rmarkdown     2.20       2023-01-19 [1] CRAN (R 4.2.2)
#>    rstudioapi    0.14       2022-08-22 [1] CRAN (R 4.2.1)
#>    sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.2.0)
#>    styler        1.9.0      2023-01-15 [1] CRAN (R 4.2.2)
#>    tibble        3.1.8      2022-07-22 [1] CRAN (R 4.2.1)
#>    tidyselect    1.2.0      2022-10-10 [1] RSPM
#>    tzdb          0.3.0      2022-03-28 [1] CRAN (R 4.2.0)
#>    utf8          1.2.3      2023-01-31 [1] CRAN (R 4.2.2)
#>    vctrs         0.5.2      2023-01-23 [1] CRAN (R 4.2.2)
#>    vroom         1.6.1      2023-01-22 [1] CRAN (R 4.2.2)
#>    withr         2.5.0      2022-03-03 [1] CRAN (R 4.2.0)
#>    xfun          0.37       2023-01-31 [1] CRAN (R 4.2.2)
#>    yaml          2.3.7      2023-01-23 [1] CRAN (R 4.2.2)
#> 
#>  [1] C:/Users/Daniel.AK-HAMBURG/AppData/Local/R/win-library/4.2
#>  [2] C:/Program Files/R/R-4.2.2/library
#> 
#>  D ── DLL MD5 mismatch, broken installation.
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by hadley** [comment] 2023-07-31 22:38
Duplicate of #1484

**Closed by hadley** 2023-07-31 22:38 UTC
