### ISSUE TITLE
parse_datetime crashes R session when providing invalid format specification

### ISSUE THREAD

**Issue by meowcat** [tidyverse/readr#1182] opened 2021-03-01 11:07 UTC
Brief description of the problem

```r
library(readr)

example("parse_datetime") # works correctly

date_chr <- "11/26/2019 8:14:41 PM"
parse_datetime(date_chr, "%m/%d/%Y %h:%M:%s %p")
```
This results in a crash of the R session.  Of course it should be `%H:%M:%S`  but it seems unnecessarily harsh to crash the entire session because of this. I originally had `%h:%m:%s` however the duplicate `%m` was not the cause.

sessionInfo:
```
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readr_1.4.0

loaded via a namespace (and not attached):
 [1] compiler_4.0.4  magrittr_2.0.1  ellipsis_0.3.1  R6_2.5.0       
 [5] hms_1.0.0       tools_4.0.4     pillar_1.4.7    tibble_3.0.6   
 [9] crayon_1.4.1    vctrs_0.3.6     lifecycle_1.0.0 pkgconfig_2.0.3
[13] rlang_0.4.10
```

**Comment by jimhester** [comment] 2021-03-01 13:38
This is a duplicate of #1151, it is already fixed by https://github.com/tidyverse/readr/commit/97186a8ac29d2058762d85b13b169e8b4ca5da71 in the development version of readr, but those changes are not currently on CRAN.

**Closed by jimhester** 2021-03-01 13:38 UTC
