### ISSUE TITLE
parse_time() fails for "12:??PM"

### ISSUE THREAD

**Issue by rmcd1024** [tidyverse/readr#618] opened 2017-02-22 00:09 UTC
`parse_time` fails for values between "12:00PM" and "12:59PM", also if you add seconds.

Here, the final value ("12:30PM") throws an error:
```
> parse_time(paste0(1:12, ':30', rep(c('AM', 'PM'), each=12)))
Warning: 1 parsing failure.
row col   expected  actual
 24  -- valid date 12:30PM
```

**Comment by jimhester** [comment] 2017-02-22 14:05
This looks to be a duplicate of https://github.com/tidyverse/readr/issues/579 and works without error with the current devel version.

``` r
readr::parse_time(paste0(1:12, ':30', rep(c('AM', 'PM'), each=12)))
#> 01:30:00
#> 02:30:00
#> 03:30:00
#> 04:30:00
#> 05:30:00
#> 06:30:00
#> 07:30:00
#> 08:30:00
#> 09:30:00
#> 10:30:00
#> 11:30:00
#> 00:30:00
#> 13:30:00
#> 14:30:00
#> 15:30:00
#> 16:30:00
#> 17:30:00
#> 18:30:00
#> 19:30:00
#> 20:30:00
#> 21:30:00
#> 22:30:00
#> 23:30:00
#> 12:30:00
```

**Closed by jimhester** 2017-02-22 14:05 UTC
