### ISSUE TITLE
Warning message for "One or more parsing issues" contains difficult to follow instruction `dat <- vroom(...)` 

### ISSUE THREAD

**Issue by charliejhadley** [tidyverse/readr#1485] opened 2023-03-20 22:10 UTC
There's been some awesome work on the on the warning messages for {readr}! However, I feel for inexperienced users the instructions are confusing.

The following error message is generated if vroom detects unexpected input:

```r
Warning message:
One or more parsing issues, call `problems()` on your data frame for details, e.g.:
  dat <- vroom(...)
  problems(dat) 
```

For a {tidyverse} user who only has the core tidyverse loaded they're not going to be able to run `dat <- vroom(...)` as they don't have `{vroom}` loaded.

However, I note that the error comes from `vroom_errors.h` in the {vroom} package... so it might not be convenient to figure out if the user has {vroom} loaded or not at the point when the error is generated.

https://github.com/tidyverse/vroom/blob/a7769d1f9216216cfd8fdc96fbde9360fe59b598/src/vroom_errors.h#L94

I think it is worth questioning if this is a useful instruction for inexperienced users even if it is decided this is the best error that can be generated.

**Comment by hadley** [comment] 2023-07-31 22:08
Duplicate of #1477

**Closed by hadley** 2023-07-31 22:08 UTC
Labels: reprex
